import type { AIArtifact, Goal, PressureHistoryRecord, Task } from '../../types/task.js';
import type { ReviewHistoryEvent, ReviewRecord } from './types.js';
import { isInsideReviewWindow } from './window.js';

export function buildReviewHistoryEvents(input: { tasks: readonly Task[]; goals: readonly Goal[]; pressureHistory: readonly PressureHistoryRecord[]; reviews: readonly ReviewRecord[]; aiArtifacts?: readonly AIArtifact[]; window: { start: string; end: string } }): ReviewHistoryEvent[] {
  const events: ReviewHistoryEvent[] = [];
  input.tasks.forEach((task) => { if (isInsideReviewWindow(task.completedAt, input.window)) events.push({ id: `task-completed:${task.id}:${task.completedAt}`, timestamp: task.completedAt!, kind: 'task_completed', title: `任务完成：${task.title}`, description: task.reviewNote, relatedTaskId: task.id }); if (isInsideReviewWindow(task.abandonedAt, input.window)) events.push({ id: `task-abandoned:${task.id}:${task.abandonedAt}`, timestamp: task.abandonedAt!, kind: 'task_abandoned', title: `任务放弃：${task.title}`, description: task.reviewNote, relatedTaskId: task.id }); });
  input.goals.forEach((goal) => (goal.milestones ?? []).forEach((milestone) => { if (milestone.status === 'completed' && isInsideReviewWindow(milestone.completedAt, input.window)) events.push({ id: `milestone:${goal.id}:${milestone.id}:${milestone.completedAt}`, timestamp: milestone.completedAt!, kind: 'milestone_completed', title: `里程碑完成：${milestone.title}`, relatedGoalId: goal.id }); }));
  input.reviews.forEach((review) => { if (isInsideReviewWindow(review.createdAt, input.window)) { events.push({ id: `review:${review.id}`, timestamp: review.createdAt, kind: 'review_saved', title: `保存复盘：${review.title}`, reviewId: review.id }); if (review.aiReport && isInsideReviewWindow(review.aiReport.generatedAt, input.window)) events.push({ id: `review-ai:${review.id}`, timestamp: review.aiReport.generatedAt, kind: 'ai_review_generated', title: `AI 复盘报告：${review.title}`, reviewId: review.id }); } });
  input.pressureHistory.filter((record) => record.eventType === 'recalibration' && isInsideReviewWindow(record.timestamp, input.window)).forEach((record) => events.push({ id: `pressure:${record.id}`, timestamp: record.timestamp, kind: 'pressure_recalibrated', title: '压力重新校准', description: record.note }));
  (input.aiArtifacts ?? []).filter((artifact) => ['review', 'task-analysis', 'pressure-analysis'].includes(artifact.kind) && isInsideReviewWindow(artifact.createdAt, input.window)).forEach((artifact) => events.push({ id: `legacy-ai:${artifact.id}`, timestamp: artifact.createdAt, kind: 'legacy_ai', title: `历史 AI 记录：${artifact.title}`, description: artifact.content }));
  return events.sort((left, right) => Date.parse(right.timestamp) - Date.parse(left.timestamp) || left.id.localeCompare(right.id));
}
