import type { ReviewAIReport, ReviewMetricsSnapshot, ReviewRecord, ReviewState, ReviewWindowDays } from './types.js';
import { isReviewWindowDays } from './window.js';

const maxReviews = 100;
const iso = (value: unknown): value is string => typeof value === 'string' && Number.isFinite(Date.parse(value));
const string = (value: unknown, max = 4000): value is string => typeof value === 'string' && value.trim().length > 0 && value.length <= max;
const finite = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value) && value >= 0;
const metricKeys: (keyof ReviewMetricsSnapshot)[] = ['resolvedCount', 'completedCount', 'abandonedCount', 'completedWithDeadlineCount', 'onTimeCompletionCount', 'lastHourCompletionCount', 'pressureSampleCount', 'highPressureSampleCount', 'activeTaskCount', 'currentOverdueTaskCount', 'currentGoalCount', 'currentMilestoneCount', 'currentCompletedMilestoneCount', 'currentScheduledTaskCount', 'currentUnscheduledTaskCount', 'currentConflictCount'];
const optionalMetricKeys: (keyof ReviewMetricsSnapshot)[] = ['completionRate', 'onTimeRate', 'averageDeadlineDeltaHours', 'averagePressure', 'maxPressure', 'pressureVolatility'];
function normalizeMetrics(value: unknown): ReviewMetricsSnapshot | undefined { if (!value || typeof value !== 'object') return undefined; const source = value as Record<string, unknown>; if (!metricKeys.every((key) => finite(source[key]))) return undefined; if (!optionalMetricKeys.every((key) => source[key] === undefined || (typeof source[key] === 'number' && Number.isFinite(source[key]) && (key === 'completionRate' || key === 'onTimeRate' ? source[key] >= 0 && source[key] <= 100 : true)))) return undefined; return { ...Object.fromEntries(metricKeys.map((key) => [key, source[key]])), ...Object.fromEntries(optionalMetricKeys.filter((key) => source[key] !== undefined).map((key) => [key, source[key]])) } as unknown as ReviewMetricsSnapshot; }
function normalizeReport(value: unknown): ReviewAIReport | undefined { if (!value || typeof value !== 'object') return undefined; const source = value as Record<string, unknown>; return string(source.content, 20000) && iso(source.generatedAt) ? { content: source.content.trim(), generatedAt: source.generatedAt, model: string(source.model, 200) ? source.model : undefined, provider: string(source.provider, 200) ? source.provider : undefined } : undefined; }
function normalizeRecord(value: unknown, ids: Set<string>): ReviewRecord | undefined { if (!value || typeof value !== 'object') return undefined; const source = value as Record<string, unknown>; if (!string(source.id, 200) || ids.has(source.id) || !isReviewWindowDays(source.windowDays) || !iso(source.windowStart) || !iso(source.windowEnd) || Date.parse(source.windowStart) >= Date.parse(source.windowEnd) || !string(source.title, 240) || !iso(source.createdAt) || !iso(source.updatedAt)) return undefined; const metrics = normalizeMetrics(source.metrics); if (!metrics) return undefined; ids.add(source.id); return { id: source.id, windowDays: source.windowDays, windowStart: source.windowStart, windowEnd: source.windowEnd, title: source.title.trim(), userNote: typeof source.userNote === 'string' && source.userNote.trim() ? source.userNote.slice(0, 4000) : undefined, metrics, aiReport: normalizeReport(source.aiReport), createdAt: source.createdAt, updatedAt: source.updatedAt }; }
export function createDefaultReviewState(now = new Date().toISOString()): ReviewState { return { schemaVersion: 1, defaultWindowDays: 7, reviews: [], updatedAt: now }; }
export function normalizeReviewState(value: unknown, now = new Date().toISOString()): ReviewState { if (!value || typeof value !== 'object' || (value as { schemaVersion?: unknown }).schemaVersion !== 1) return createDefaultReviewState(now); const source = value as Record<string, unknown>; const ids = new Set<string>(); const reviews = Array.isArray(source.reviews) ? source.reviews.flatMap((record) => { const next = normalizeRecord(record, ids); return next ? [next] : []; }).sort((left, right) => right.createdAt.localeCompare(left.createdAt)).slice(0, maxReviews) : []; return { schemaVersion: 1, defaultWindowDays: isReviewWindowDays(source.defaultWindowDays) ? source.defaultWindowDays : 7, reviews, updatedAt: iso(source.updatedAt) ? source.updatedAt : now }; }
export function chooseNewerReviewState(local: unknown, cloud: unknown): ReviewState { const left = normalizeReviewState(local); const right = normalizeReviewState(cloud); return Date.parse(right.updatedAt) > Date.parse(left.updatedAt) ? right : left; }
export function addReviewRecord(state: ReviewState, record: ReviewRecord): ReviewState { const base = normalizeReviewState(state, record.updatedAt); return normalizeReviewState({ ...base, reviews: [record, ...base.reviews.filter((entry) => entry.id !== record.id)], updatedAt: record.updatedAt }, record.updatedAt); }
export function deleteReviewRecord(state: ReviewState, id: string, now: string): ReviewState { const base = normalizeReviewState(state, now); return { ...base, reviews: base.reviews.filter((record) => record.id !== id), updatedAt: now }; }
export function createReviewRecord(input: { id: string; windowDays: ReviewWindowDays; windowStart: string; windowEnd: string; metrics: ReviewMetricsSnapshot; userNote?: string; aiReport?: ReviewAIReport; now: string }): ReviewRecord { return { id: input.id, windowDays: input.windowDays, windowStart: input.windowStart, windowEnd: input.windowEnd, title: `近 ${input.windowDays} 天复盘 · ${input.now.slice(0, 10)}`, userNote: input.userNote?.trim() || undefined, metrics: input.metrics, aiReport: input.aiReport, createdAt: input.now, updatedAt: input.now }; }
