import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const ops = await import('./.compiled/src/domain/ops/types.js');
const normalization = await import('./.compiled/src/domain/ops/normalization.js');
const dependencies = await import('./.compiled/src/domain/ops/dependencies.js');
const scheduler = await import('./.compiled/src/domain/ops/scheduler.js');
const plans = await import('./.compiled/src/domain/ops/plans.js');
const now = '2026-09-21T00:00:00.000Z';
const task = (id, patch = {}) => ({ id, title: id, importance: 5, progress: 0, taskProgress: 0, activityType: 'task', lifecycleStatus: 'active', schemaVersion: 3, createdAt: now, updatedAt: now, ...patch });
const available = (state, executor = 'self') => ({ ...state, executors: state.executors.map((item) => item.id === executor ? { ...item, availability: [{ id: `${executor}-mon`, weekday: 1, startTime: '08:00', endTime: '18:00' }] } : item) });

test('OPS default state fabricates no availability and safe normalization omits invalid records', () => { const state = ops.createDefaultOpsState(now); assert.deepEqual(state.executors[0].availability, []); const normalized = normalization.normalizeOpsState({ ...state, executors: [{ ...state.executors[0], kind: 'wrong' }, { ...state.executors[0], id: 'self', availability: [{ id: 'bad', weekday: 0, startTime: '99:00', endTime: '10:00' }] }] }, now); assert.equal(normalized.executors.length, 1); assert.deepEqual(normalized.executors[0].availability, []); });
test('missing duration and no availability are explicit rather than fabricated', () => { const state = ops.createDefaultOpsState(now); assert.equal(scheduler.buildOpsScheduleProposal({ tasks: [task('none')], goals: [], state, now }).unscheduled[0].reason, 'MISSING_DURATION'); assert.equal(scheduler.buildOpsScheduleProposal({ tasks: [task('duration', { estimatedDuration: 30 })], goals: [], state, now }).unscheduled[0].reason, 'NO_AVAILABILITY'); });
test('scheduler places a fitting task in its first legal slot deterministically without mutating input', () => { const state = available(ops.createDefaultOpsState(now)); const source = [task('a', { estimatedDuration: 60 })]; const first = scheduler.buildOpsScheduleProposal({ tasks: source, goals: [], state, now, id: 'p' }); const second = scheduler.buildOpsScheduleProposal({ tasks: source, goals: [], state, now, id: 'p' }); assert.equal(first.allocations[0].start, '2026-09-21T08:00:00.000Z'); assert.deepEqual(first, second); assert.equal(source[0].startDate, undefined); });
test('same executor serializes maxParallel one while different executor lanes overlap', () => { let state = available(ops.createDefaultOpsState(now)); const serial = scheduler.buildOpsScheduleProposal({ tasks: [task('a', { estimatedDuration: 60 }), task('b', { estimatedDuration: 60 })], goals: [], state, now }); assert.equal(serial.allocations[0].end, serial.allocations[1].start); state = { ...state, executors: [...state.executors, { id: 'gpu', name: 'GPU', kind: 'compute', active: true, maxParallel: 1, availability: [{ id: 'gpu-mon', weekday: 1, startTime: '08:00', endTime: '18:00' }] }], taskConfigs: [{ taskId: 'b', executorId: 'gpu', updatedAt: now }] }; const parallel = scheduler.buildOpsScheduleProposal({ tasks: [task('a', { estimatedDuration: 60 }), task('b', { estimatedDuration: 60 })], goals: [], state, now }); assert.equal(parallel.allocations[0].start, parallel.allocations[1].start); });
test('commitments block slots and predecessor constraints are genuine dependencies', () => { let state = available(ops.createDefaultOpsState(now)); state = { ...state, commitments: [{ id: 'meeting', title: 'meeting', executorId: 'self', start: '2026-09-21T08:00:00.000Z', end: '2026-09-21T09:00:00.000Z', locked: true, source: 'manual', createdAt: now, updatedAt: now }] }; const blocked = scheduler.buildOpsScheduleProposal({ tasks: [task('a', { estimatedDuration: 60 })], goals: [], state, now }); assert.equal(blocked.allocations[0].start, '2026-09-21T09:00:00.000Z'); const dependency = scheduler.buildOpsScheduleProposal({ tasks: [task('a', { estimatedDuration: 60 }), task('b', { estimatedDuration: 60, dependencyIds: ['a'] })], goals: [], state: available(ops.createDefaultOpsState(now)), now }); const byTask = new Map(dependency.allocations.map((entry) => [entry.taskId, entry])); assert.equal(byTask.get('a').end, byTask.get('b').start); });
test('dependency projection handles completed, missing, self and cycles without creating edges from order', () => { const graph = dependencies.projectTaskDependencyGraph([task('done', { lifecycleStatus: 'completed' }), task('ok', { dependencyIds: ['done'] }), task('missing', { dependencyIds: ['gone'] }), task('self', { dependencyIds: ['self'] }), task('a', { dependencyIds: ['b'] }), task('b', { dependencyIds: ['a'] })]); assert.equal(graph.find((entry) => entry.taskId === 'ok').predecessors[0].state, 'satisfied'); assert.equal(graph.find((entry) => entry.taskId === 'missing').predecessors[0].state, 'missing'); assert.equal(graph.find((entry) => entry.taskId === 'self').predecessors[0].state, 'self'); assert.equal(graph.find((entry) => entry.taskId === 'a').predecessors[0].state, 'cycle'); });
test('deadline risks, horizon overflow and terminal tasks are reported safely', () => { const state = available(ops.createDefaultOpsState(now)); const plan = scheduler.buildOpsScheduleProposal({ tasks: [task('late', { estimatedDuration: 60, deadline: '2026-09-21T08:30:00.000Z' }), task('done', { estimatedDuration: 60, lifecycleStatus: 'completed' })], goals: [], state, now }); assert.ok(plan.warnings.includes('DEADLINE_MISS:late')); assert.equal(plan.allocations.some((entry) => entry.taskId === 'done'), false); const overflow = scheduler.buildOpsScheduleProposal({ tasks: [task('huge', { estimatedDuration: 900 })], goals: [], state, now, horizonEnd: '2026-09-21T09:00:00.000Z' }); assert.equal(overflow.unscheduled[0].reason, 'NO_CAPACITY_IN_HORIZON'); });
test('proposal acceptance/rejection keeps accepted authority and locked work survives replan', () => { const base = available(ops.createDefaultOpsState(now)); const accepted = { id: 'old', version: 1, status: 'accepted', horizonStart: now, horizonEnd: '2026-09-28T00:00:00.000Z', allocations: [{ taskId: 'a', executorId: 'self', start: '2026-09-21T10:00:00.000Z', end: '2026-09-21T11:00:00.000Z', effortMinutes: 60, elapsedMinutes: 60, locked: true, source: 'manual' }], unscheduled: [], warnings: [], createdAt: now }; const state = { ...base, plans: [accepted], acceptedPlanId: 'old' }; const proposal = scheduler.buildOpsScheduleProposal({ tasks: [task('a', { estimatedDuration: 60 }), task('b', { estimatedDuration: 60 })], goals: [], state, now, id: 'new' }); assert.equal(proposal.allocations.find((entry) => entry.taskId === 'a').start, accepted.allocations[0].start); const proposedState = plans.addOpsProposal(state, proposal, now); assert.equal(proposedState.acceptedPlanId, 'old'); const rejected = plans.rejectOpsPlan(proposedState, 'new', now); assert.equal(rejected.acceptedPlanId, 'old'); const acceptedState = plans.acceptOpsPlan(proposedState, 'new', now); assert.equal(acceptedState.acceptedPlanId, 'new'); assert.equal(acceptedState.plans.find((entry) => entry.id === 'old').status, 'superseded'); });
test('manual scheduling is separate from Task fields and cleanup only removes matching OPS references', () => { const base = available(ops.createDefaultOpsState(now)); const manual = plans.upsertManualAllocation(base, { taskId: 'a', executorId: 'self', start: '2026-09-21T08:00:00.000Z', end: '2026-09-21T09:00:00.000Z', effortMinutes: 30, elapsedMinutes: 60, locked: true, source: 'manual' }, now); const configured = plans.upsertOpsTaskConfig(manual, { taskId: 'b', executorId: 'self', effortMinutes: 20, updatedAt: now }, now); const cleaned = plans.deleteTaskFromOpsState(configured, 'a', now); assert.equal(cleaned.plans[0].allocations.length, 0); assert.equal(cleaned.taskConfigs[0].taskId, 'b'); });
test('newer valid cloud OPS state wins while ties preserve local owner state', () => { const local = ops.createDefaultOpsState(now); const cloud = { ...ops.createDefaultOpsState('2026-09-22T00:00:00.000Z'), timezone: 'Asia/Shanghai' }; assert.equal(normalization.chooseNewerOpsState(local, cloud).timezone, 'Asia/Shanghai'); assert.equal(normalization.chooseNewerOpsState(local, { ...local }).timezone, local.timezone); });
test('OPS route uses the dedicated page and neither LifeOSPlanner nor Task CRUD becomes authority', () => { const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8'); const page = readFileSync(new URL('../src/components/OpsPage.tsx', import.meta.url), 'utf8'); const inventory = readFileSync(new URL('../src/storage/inventory.ts', import.meta.url), 'utf8'); assert.match(app, /publicPath === '\/app\/ops'[\s\S]*<OpsPage/); assert.doesNotMatch(page, /LifeOSPlanner|onAddTask|onSaveGoal|Top 3/); assert.match(page, /TIMELINE[\s\S]*DEPENDENCIES[\s\S]*CAPACITY/); assert.match(inventory, /operations\.v2-state/); });
