import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const hierarchy = await import('./.compiled/src/domain/plan/hierarchy.js');
const decomposition = await import('./.compiled/src/domain/plan/decomposition.js');
const now = '2026-09-23T10:00:00.000Z';
const task = (id, patch = {}) => ({ id, title: id, importance: 5, progress: 0, taskProgress: 0, activityType: 'task', lifecycleStatus: 'active', schemaVersion: 3, createdAt: now, updatedAt: now, ...patch });
const goal = (id, patch = {}) => ({ id, title: id, category: 'task', priority: 5, linkedTaskIds: [], createdAt: now, updatedAt: now, ...patch });
const milestone = (id, title = id, patch = {}) => ({ id, title, sequence: 1, status: 'planned', createdAt: now, updatedAt: now, ...patch });

test('old goal with no milestones normalizes to an empty compatibility array', () => assert.deepEqual(hierarchy.normalizeGoalMilestones(undefined, now), []));
test('milestone creation preserves a supplied stable ID and deterministic default shape', () => { const created = hierarchy.createGoalMilestone({ title: 'research' }, now, 'm-1'); assert.equal(created.id, 'm-1'); assert.equal(created.sequence, 1); assert.equal(created.status, 'planned'); });
test('reordering milestones keeps IDs and renormalizes sequences', () => { const source = goal('g', { milestones: [milestone('a'), milestone('b', 'b', { sequence: 2 })] }); const result = hierarchy.reorderGoalMilestones(source, ['b', 'a'], now); assert.deepEqual(result.milestones.map((item) => [item.id, item.sequence]), [['b', 1], ['a', 2]]); });
test('deleting milestone keeps tasks and goal links while clearing only milestoneId', () => { const source = goal('g', { milestones: [milestone('m')] }); const result = hierarchy.deleteMilestoneWithTaskCleanup([source], [task('t', { milestoneId: 'm', linkedGoalIds: ['g'] })], 'g', 'm', now); assert.equal(result.goals[0].milestones.length, 0); assert.equal(result.tasks[0].milestoneId, undefined); assert.deepEqual(result.tasks[0].linkedGoalIds, ['g']); });
test('assigning a task keeps unrelated links and writes both goal relationship sides', () => { const result = hierarchy.assignTaskToMilestone([goal('g', { milestones: [milestone('m')] }), goal('other', { linkedTaskIds: ['t'] })], [task('t', { linkedGoalIds: ['other'] })], 't', 'g', 'm', now); assert.equal(result.tasks[0].milestoneId, 'm'); assert.deepEqual(result.tasks[0].linkedGoalIds.sort(), ['g', 'other']); assert.deepEqual(result.goals[0].linkedTaskIds, ['t']); assert.deepEqual(result.goals[1].linkedTaskIds, ['t']); });
test('unassigning a task preserves the goal relation', () => { const result = hierarchy.unassignTaskFromMilestone([task('t', { milestoneId: 'm', linkedGoalIds: ['g'] })], 't', now); assert.equal(result[0].milestoneId, undefined); assert.deepEqual(result[0].linkedGoalIds, ['g']); });
test('deleting a goal clears its milestone reference and links while preserving task', () => { const result = hierarchy.deleteGoalWithPlanCleanup([goal('g', { milestones: [milestone('m')] })], [task('t', { milestoneId: 'm', linkedGoalIds: ['g', 'other'] })], 'g', now); assert.equal(result.goals.length, 0); assert.equal(result.tasks[0].milestoneId, undefined); assert.deepEqual(result.tasks[0].linkedGoalIds, ['other']); });
test('invalid milestone references are warnings and do not fabricate milestones', () => { const result = hierarchy.validatePlanHierarchy([goal('g')], [task('t', { milestoneId: 'missing' })]); assert.equal(result.errors.length, 0); assert.match(result.warnings.join(' '), /不存在/); });
test('progress projection is deterministic for empty and mixed hierarchy', () => { assert.equal(hierarchy.projectGoalPlanProgress(goal('empty'), []).progress, 0); const output = hierarchy.projectGoalPlanProgress(goal('g', { milestones: [milestone('m1', 'm1', { status: 'completed' }), milestone('m2', 'm2', { sequence: 2 })] }), [task('a', { linkedGoalIds: ['g'], lifecycleStatus: 'completed' }), task('b', { linkedGoalIds: ['g'] })]); assert.deepEqual(output, { milestoneTotal: 2, milestoneCompleted: 1, taskTotal: 2, taskCompleted: 1, progress: 50 }); });
test('decomposition parser rejects malformed JSON, duplicate IDs, impossible dates, bad edges, self edges and cycles', () => { assert.equal(decomposition.parseGoalDecomposition('{').ok, false); assert.equal(decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [{ id: 'm', title: 'a' }, { id: 'm', title: 'b' }], tasks: [] })).ok, false); assert.equal(decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [], tasks: [{ id: 't', title: 't', deadline: '2026-99-99' }] })).ok, false); assert.equal(decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [], tasks: [{ id: 't', title: 't', dependencyDraftIds: ['gone'] }] })).ok, false); assert.equal(decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [], tasks: [{ id: 't', title: 't', dependencyDraftIds: ['t'] }] })).ok, false); assert.equal(decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [], tasks: [{ id: 'a', title: 'a', dependencyDraftIds: ['b'] }, { id: 'b', title: 'b', dependencyDraftIds: ['a'] }] })).ok, false); });
test('valid decomposition accepts standalone tasks and clamps importance into the safe range', () => { const result = decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [{ id: 'm', title: 'M' }], tasks: [{ id: 'a', title: 'standalone', importance: 99 }, { id: 'b', title: 'linked', importance: 1, milestoneDraftId: 'm', dependencyDraftIds: ['a'] }] })); assert.equal(result.ok, true); if (result.ok) { assert.equal(result.value.tasks[0].importance, 10); assert.equal(result.value.tasks[0].milestoneDraftId, undefined); } });
test('duplicate exact task title is warned and safely excluded by default, but may be explicitly included', () => { const result = decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [], tasks: [{ id: 'a', title: 'exists', importance: 5 }] }), [task('old', { title: 'exists' })]); assert.equal(result.ok, true); if (result.ok) { assert.equal(result.value.tasks[0].included, false); result.value.tasks[0].included = true; assert.equal(decomposition.buildGoalDecompositionMaterializationPlan(goal('g'), result.value).tasks.length, 1); } });
test('duplicate milestone title is excluded before review but can be re-included deliberately', () => { const result = decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [{ id: 'm', title: 'exists' }], tasks: [] }), [], ['exists']); assert.equal(result.ok, true); if (result.ok) { assert.equal(result.value.milestones[0].included, false); assert.match(result.value.milestones[0].duplicateWarning, /重复/); result.value.milestones[0].included = true; assert.equal(decomposition.buildGoalDecompositionMaterializationPlan(goal('g'), result.value).milestones.length, 1); } });
test('materialization is pure, excludes review drafts, allocates IDs before output, and maps relationships', () => { const parsed = decomposition.parseGoalDecomposition(JSON.stringify({ milestones: [{ id: 'm', title: 'M' }, { id: 'skip', title: 'skip' }], tasks: [{ id: 'a', title: 'A', importance: 5, milestoneDraftId: 'm' }, { id: 'b', title: 'B', importance: 6, milestoneDraftId: 'm', dependencyDraftIds: ['a'] }, { id: 'skip-task', title: 'skip task', importance: 5 }] })); assert.equal(parsed.ok, true); if (!parsed.ok) return; parsed.value.milestones[1].included = false; parsed.value.tasks[2].included = false; const plan = decomposition.buildGoalDecompositionMaterializationPlan(goal('g'), parsed.value, now); assert.equal(plan.milestones.length, 1); assert.equal(plan.tasks.length, 2); assert.equal(plan.tasks[0].input.linkedGoalIds[0], 'g'); assert.equal(plan.tasks[0].input.milestoneId, plan.milestones[0].id); assert.equal(plan.tasks[1].input.dependencyIds[0], plan.tasks[0].id); });
test('PLAN route uses the focused PlanPage and does not render LifeOSPlanner responsibilities', () => { const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8'); const page = readFileSync(new URL('../src/components/PlanPage.tsx', import.meta.url), 'utf8'); assert.match(app, /<PlanPage[\s\S]*ownerKey=/); assert.doesNotMatch(app, /<LifeMapPage/); assert.doesNotMatch(page, /LifeOSPlanner|ResourceEditor|7-day planner|Gantt|Top 3|现在做什么/); assert.match(page, /AI 分解草稿/); assert.match(page, /添加里程碑/); assert.match(page, /未分配任务/); });
test('PLAN decomposition uses the goal_decompose AI mode and owner switch clears draft state', () => { const page = readFileSync(new URL('../src/components/PlanPage.tsx', import.meta.url), 'utf8'); const ai = readFileSync(new URL('../src/services/aiClient.ts', import.meta.url), 'utf8'); assert.match(page, /mode: 'goal_decompose'/); assert.match(page, /\[props\.ownerKey\]/); assert.match(ai, /'goal_decompose'/); });
test('review exposes required editable decomposition fields and human-readable ambiguity notes', () => { const page = readFileSync(new URL('../src/components/PlanPage.tsx', import.meta.url), 'utf8'); assert.match(page, /目标日期/); assert.match(page, /成功标准/); assert.match(page, /截止日期/); assert.match(page, /预计分钟/); assert.match(page, /依赖（可移除）/); assert.match(page, /需要注意/); assert.match(page, /说明/); });
