import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const review = await import('./.compiled/src/domain/review/index.js');
const ops = await import('./.compiled/src/domain/ops/types.js');
const now = '2026-09-24T12:00:00.000Z';
const task = (id, patch = {}) => ({ id, title: id, importance: 5, progress: 0, taskProgress: 0, activityType: 'task', lifecycleStatus: 'active', schemaVersion: 3, createdAt: now, updatedAt: now, ...patch });
const goals = () => [{ id: 'g', title: 'G', category: 'work', priority: 5, linkedTaskIds: [], createdAt: now, updatedAt: now, milestones: [{ id: 'm', title: 'M', sequence: 1, status: 'completed', createdAt: now, updatedAt: now, completedAt: '2026-09-22T00:00:00.000Z' }] }];
const window = review.createReviewWindow(7, now);
const state = ops.createDefaultOpsState(now);

test('review windows use completion and abandonment timestamps, never updatedAt, with an honest empty denominator', () => { const metrics = review.deriveReviewMetrics({ tasks: [task('completed', { lifecycleStatus: 'completed', completedAt: '2026-09-23T12:00:00.000Z' }), task('abandoned', { lifecycleStatus: 'abandoned', abandonedAt: '2026-09-22T12:00:00.000Z' }), task('changed-only', { lifecycleStatus: 'active', updatedAt: '2026-09-23T12:00:00.000Z' })], goals: [], pressureHistory: [], opsState: state, window, now }); assert.equal(metrics.completedCount, 1); assert.equal(metrics.abandonedCount, 1); assert.equal(metrics.resolvedCount, 2); assert.equal(metrics.completionRate, 50); assert.equal(review.deriveReviewMetrics({ tasks: [task('none')], goals: [], pressureHistory: [], opsState: state, window, now }).completionRate, undefined); });
test('deadline metrics retain positive and negative deltas, and final hour never includes late completions', () => { const metrics = review.deriveReviewMetrics({ tasks: [task('early', { lifecycleStatus: 'completed', completedAt: '2026-09-23T11:30:00.000Z', deadline: '2026-09-23T12:00:00.000Z' }), task('late', { lifecycleStatus: 'completed', completedAt: '2026-09-23T13:00:00.000Z', deadline: '2026-09-23T12:00:00.000Z' }), task('invalid', { lifecycleStatus: 'completed', completedAt: '2026-09-23T11:00:00.000Z', deadline: 'bad' })], goals: [], pressureHistory: [], opsState: state, window, now }); assert.equal(metrics.completedWithDeadlineCount, 2); assert.equal(metrics.onTimeCompletionCount, 1); assert.equal(metrics.lastHourCompletionCount, 1); assert.equal(metrics.averageDeadlineDeltaHours, -0.25); });
test('pressure metrics are window-bounded, deterministic, and report samples rather than invented days', () => { const metrics = review.deriveReviewMetrics({ tasks: [], goals: [], opsState: state, window, now, pressureHistory: [{ id: 'old', timestamp: '2026-09-01T00:00:00.000Z', pressure: 99, currentTaskLoad: 0, activeTaskCount: 0, completedToday: 0, abandonedToday: 0, recoveryRelief: 0 }, { id: 'one', timestamp: '2026-09-23T00:00:00.000Z', pressure: 81, currentTaskLoad: 0, activeTaskCount: 0, completedToday: 0, abandonedToday: 0, recoveryRelief: 0 }, { id: 'two', timestamp: '2026-09-23T02:00:00.000Z', pressure: 61, currentTaskLoad: 0, activeTaskCount: 0, completedToday: 0, abandonedToday: 0, recoveryRelief: 0 }] }); assert.equal(metrics.pressureSampleCount, 2); assert.equal(metrics.averagePressure, 71); assert.equal(metrics.maxPressure, 81); assert.equal(metrics.highPressureSampleCount, 1); assert.equal(review.deriveReviewMetrics({ tasks: [], goals: [], opsState: state, window, now, pressureHistory: [] }).averagePressure, undefined); });
test('history projects only factual events and remains deterministic newest first', () => { const events = review.buildReviewHistoryEvents({ tasks: [task('done', { lifecycleStatus: 'completed', completedAt: '2026-09-23T00:00:00.000Z', reviewNote: 'fact' }), task('gone', { lifecycleStatus: 'abandoned', abandonedAt: '2026-09-22T00:00:00.000Z' }), task('no-proof', { updatedAt: '2026-09-23T10:00:00.000Z' })], goals: goals(), pressureHistory: [{ id: 'auto', timestamp: '2026-09-23T09:00:00.000Z', pressure: 50, currentTaskLoad: 0, activeTaskCount: 0, completedToday: 0, abandonedToday: 0, recoveryRelief: 0, eventType: 'auto' }, { id: 'cal', timestamp: '2026-09-23T08:00:00.000Z', pressure: 50, currentTaskLoad: 0, activeTaskCount: 0, completedToday: 0, abandonedToday: 0, recoveryRelief: 0, eventType: 'recalibration' }], reviews: [], window }); assert.ok(events.some((event) => event.kind === 'task_completed')); assert.ok(events.some((event) => event.kind === 'task_abandoned')); assert.ok(events.some((event) => event.kind === 'milestone_completed')); assert.ok(events.some((event) => event.kind === 'pressure_recalibrated')); assert.equal(events.some((event) => event.id.includes('auto')), false); assert.deepEqual(events, [...events].sort((a, b) => Date.parse(b.timestamp) - Date.parse(a.timestamp) || a.id.localeCompare(b.id))); });
test('daily trends zero-fill selected windows and group actual completion and pressure samples in OPS timezone', () => { const trends = review.buildReviewDailyTrends({ tasks: [task('cn', { lifecycleStatus: 'completed', completedAt: '2026-09-23T01:30:00.000Z' }), task('ab', { lifecycleStatus: 'abandoned', abandonedAt: '2026-09-23T01:30:00.000Z' })], pressureHistory: [{ id: 'p', timestamp: '2026-09-23T01:30:00.000Z', pressure: 70, currentTaskLoad: 0, activeTaskCount: 0, completedToday: 0, abandonedToday: 0, recoveryRelief: 0 }], window, timezone: 'Asia/Shanghai' }); assert.equal(trends.length, 7); const chinaDay = trends.find((entry) => entry.completedCount === 1); assert.equal(chinaDay?.abandonedCount, 1); assert.equal(chinaDay?.averagePressure, 70); assert.ok(trends.some((entry) => entry.completedCount === 0 && entry.abandonedCount === 0)); });
test('saved records freeze metrics, bound history, normalize invalid data and delete only the requested review', () => { const metrics = review.deriveReviewMetrics({ tasks: [task('done', { lifecycleStatus: 'completed', completedAt: '2026-09-23T00:00:00.000Z' })], goals: [], pressureHistory: [], opsState: state, window, now }); const record = review.createReviewRecord({ id: 'one', windowDays: 7, windowStart: window.start, windowEnd: window.end, metrics, now }); const saved = review.addReviewRecord(review.createDefaultReviewState(now), record); assert.equal(saved.reviews[0].metrics.completedCount, 1); assert.equal(review.deleteReviewRecord(saved, 'one', now).reviews.length, 0); const many = review.normalizeReviewState({ schemaVersion: 1, defaultWindowDays: 7, updatedAt: now, reviews: Array.from({ length: 105 }, (_, index) => ({ ...record, id: `r-${index}`, createdAt: `2026-09-24T${String(index % 10).padStart(2, '0')}:00:00.000Z`, updatedAt: now })) }); assert.equal(many.reviews.length, 100); assert.equal(review.normalizeReviewState({ schemaVersion: 1, defaultWindowDays: 7, updatedAt: now, reviews: [{ ...record, id: '', windowEnd: window.start }] }).reviews.length, 0); });
test('review AI payload is bounded and excludes profile, while prompt states factual and psychological boundaries', () => { const input = review.buildReviewAnalysisInput({ window, metrics: review.deriveReviewMetrics({ tasks: [], goals: [], pressureHistory: [], opsState: state, window, now }), tasks: Array.from({ length: 60 }, (_, index) => task(`t-${index}`, { lifecycleStatus: 'completed', completedAt: '2026-09-23T00:00:00.000Z' })), pressureHistory: [], opsState: state }); assert.equal(input.resolvedTasks.length, 50); assert.equal(JSON.stringify(input).includes('UserProfile'), false); assert.match(review.reviewAnalysisSystemPrompt, /事实与解释/); assert.match(review.reviewAnalysisSystemPrompt, /心理健康诊断/); });
test('review wiring uses a dedicated page, owner-scoped state, profile JSON cloud persistence, and no legacy LogPage route', () => { const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8'); const page = readFileSync(new URL('../src/components/ReviewPage.tsx', import.meta.url), 'utf8'); const cloud = readFileSync(new URL('../src/lib/cloudSync.ts', import.meta.url), 'utf8'); const inventory = readFileSync(new URL('../src/storage/inventory.ts', import.meta.url), 'utf8'); assert.match(app, /storageKeys\.reviewState/); assert.match(app, /reviewStateReady/); assert.match(app, /publicPath === '\/app\/review'[\s\S]*<ReviewPage/); assert.doesNotMatch(app.match(/publicPath === '\/app\/review'[\s\S]{0,800}/)?.[0] ?? '', /<LogPage/); assert.match(page, /OVERVIEW[\s\S]*HISTORY[\s\S]*TRENDS[\s\S]*REPORTS/); assert.match(page, /近 \{days\} 天/); assert.match(page, /保存复盘/); assert.match(page, /生成 AI 分析/); assert.doesNotMatch(page, /BMI|wearable|onDelete=|onRecalibrate/); assert.match(cloud, /reviewState/); assert.match(inventory, /review\.v2-state/); });
