import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const { defaultTaskFilters, deleteTaskWithReferences, filterTasks, getBlockedState, reconcileTaskGoalLinks, sortTasks, transitionTaskLifecycle, validateTaskDraft } = await import('./.compiled/src/domain/tasks/operations.js');
const now = new Date('2026-09-22T10:00:00.000Z');
const task = (id, patch = {}) => ({ id, title: id, importance: 5, progress: 0, activityType: 'task', lifecycleStatus: 'active', schemaVersion: 3, createdAt: '2026-09-20T10:00:00.000Z', updatedAt: '2026-09-21T10:00:00.000Z', ...patch });
const goal = (id, linkedTaskIds = []) => ({ id, title: id, category: 'task', priority: 5, linkedTaskIds, createdAt: '2026-09-20T10:00:00.000Z', updatedAt: '2026-09-20T10:00:00.000Z' });
const input = (patch = {}) => ({ title: 'new task', importance: 5, progress: 0, activityType: 'task', lifecycleStatus: 'active', progressMode: 'manual', ...patch });

test('manual new task defaults are standalone with no fabricated deadline', () => { const draft = input(); assert.equal(draft.deadline, undefined); assert.equal(validateTaskDraft(draft, [], []).errors.length, 0); });
test('goal reconciliation maintains both task and goal relationship sides', () => { const current = task('t', { linkedGoalIds: ['old'] }); const goals = [goal('old', ['t']), goal('new')]; const linked = reconcileTaskGoalLinks([current], goals, { ...current, linkedGoalIds: ['new'], updatedAt: '2026-09-22T10:00:00.000Z' }, ['old']); assert.deepEqual(linked.tasks[0].linkedGoalIds, ['new']); assert.deepEqual(linked.goals[0].linkedTaskIds, []); assert.deepEqual(linked.goals[1].linkedTaskIds, ['t']); });
test('delete cleanup removes goal and predecessor references only for deleted task', () => { const cleaned = deleteTaskWithReferences([task('a'), task('b', { dependencyIds: ['a', 'c'] }), task('c')], [goal('g', ['a', 'c'])], 'a'); assert.deepEqual(cleaned.tasks.map((item) => item.id), ['b', 'c']); assert.deepEqual(cleaned.tasks[0].dependencyIds, ['c']); assert.deepEqual(cleaned.goals[0].linkedTaskIds, ['c']); });
test('dependency validation rejects self, missing, duplicate-normalizes, and rejects cycles', () => { const a = task('a', { dependencyIds: ['b'] }); const b = task('b'); assert.match(validateTaskDraft(input({ dependencyIds: ['a'] }), [a, b], [], 'a').errors.join(' '), /自己/); assert.match(validateTaskDraft(input({ dependencyIds: ['missing'] }), [a, b], []).errors.join(' '), /不存在/); assert.deepEqual(validateTaskDraft(input({ dependencyIds: ['b', 'b'] }), [a, b], []).dependencyIds, ['b']); assert.match(validateTaskDraft(input({ dependencyIds: ['a'] }), [a, b], [], 'b').errors.join(' '), /循环/); const c = task('c', { dependencyIds: ['a'] }); assert.match(validateTaskDraft(input({ dependencyIds: ['c'] }), [a, b, c], [], 'b').errors.join(' '), /循环/); assert.equal(validateTaskDraft(input({ dependencyIds: ['b'] }), [task('b')], []).errors.length, 0); });
test('blocked projection distinguishes incomplete, completed, and missing predecessors', () => { assert.equal(getBlockedState(task('x', { dependencyIds: ['a'] }), [task('a')]).blocked, true); assert.equal(getBlockedState(task('x', { dependencyIds: ['a'] }), [task('a', { lifecycleStatus: 'completed', progress: 100 })]).blocked, false); assert.deepEqual(getBlockedState(task('x', { dependencyIds: ['lost'] }), []).missingDependencyIds, ['lost']); });
test('lifecycle transitions preserve complete, abandon, and restore semantics', () => { const original = task('a'); const completed = transitionTaskLifecycle(original, 'completed', '2026-09-22T12:00:00.000Z'); assert.equal(completed.progress, 100); assert.ok(completed.completedAt); const abandoned = transitionTaskLifecycle(original, 'abandoned', '2026-09-22T12:00:00.000Z'); assert.equal(abandoned.lifecycleStatus, 'abandoned'); assert.ok(abandoned.abandonedAt); const restored = transitionTaskLifecycle(completed, 'active', '2026-09-22T13:00:00.000Z'); assert.equal(restored.lifecycleStatus, 'active'); assert.equal(restored.completedAt, undefined); assert.equal(restored.progress, 0); });
test('filters cover lifecycle, category, goal, deadlines, and text search', () => { const tasks = [task('over', { title: 'write notes', description: 'alpha', deadline: '2026-09-21T10:00:00.000Z', linkedGoalIds: ['g'] }), task('none', { activityType: 'research', nextAction: 'read beta' }), task('done', { lifecycleStatus: 'completed', progress: 100 })]; assert.equal(filterTasks(tasks, { ...defaultTaskFilters, lifecycle: 'all', deadline: 'overdue' }, now).length, 1); assert.equal(filterTasks(tasks, { ...defaultTaskFilters, activityType: 'research' }, now)[0].id, 'none'); assert.equal(filterTasks(tasks, { ...defaultTaskFilters, goalId: 'g' }, now)[0].id, 'over'); assert.equal(filterTasks(tasks, { ...defaultTaskFilters, deadline: 'no_deadline' }, now)[0].id, 'none'); assert.equal(filterTasks(tasks, { ...defaultTaskFilters, lifecycle: 'all', query: 'beta' }, now)[0].id, 'none'); });
test('sorts remain deterministic for deadline, importance, priority and updated ties', () => { const tasks = [task('b', { importance: 9, deadline: '2026-09-24T10:00:00.000Z', updatedAt: '2026-09-22T10:00:00.000Z' }), task('a', { importance: 9, deadline: '2026-09-23T10:00:00.000Z', updatedAt: '2026-09-22T10:00:00.000Z' })]; assert.deepEqual(sortTasks(tasks, 'deadline', now).map((item) => item.id), ['a', 'b']); assert.deepEqual(sortTasks(tasks, 'importance', now).map((item) => item.id), ['a', 'b']); assert.deepEqual(sortTasks(tasks, 'updated', now).map((item) => item.id), ['a', 'b']); assert.equal(sortTasks(tasks, 'priority', now)[0].id, 'a'); });
test('matrix eligibility is active-only after lifecycle filtering', () => { const tasks = [task('active'), task('done', { lifecycleStatus: 'completed', progress: 100 })]; assert.deepEqual(filterTasks(tasks, { ...defaultTaskFilters, lifecycle: 'active' }, now).map((item) => item.id), ['active']); });
test('TASKS UI keeps task terminology and deterministic manual CRUD boundaries', () => { const page = readFileSync(new URL('../src/components/TaskPage.tsx', import.meta.url), 'utf8'); const form = readFileSync(new URL('../src/components/TaskForm.tsx', import.meta.url), 'utf8'); assert.doesNotMatch(page, /AITaskCommandBar|Gantt|scheduler|项目/); assert.doesNotMatch(form, /项目/); assert.match(form, /预计时长（分钟）/); assert.match(form, /关联目标/); assert.match(form, /前置任务 \/ Blocked by/); assert.match(page, /tasks=\{normalizedTasks\}|TASKS/); });
