import { useMemo, useState } from 'react';
import type { Goal, Task } from '../../types/task';
import { annualGoals, lifeStages, projects, statusLabels } from './data';
import { TimelineSidebar } from './TimelineSidebar';
import type { TimelineItem, TimelineStatus, TimelineZoom } from './types';

interface Props { goals: Goal[]; tasks: Task[] }
const zooms: { id: TimelineZoom; label: string }[] = [{ id: 'life', label: '人生全景' }, { id: 'decade', label: '10 年' }, { id: 'year', label: '1 年' }, { id: 'month', label: '1 月' }, { id: 'week', label: '本周' }, { id: 'day', label: '今日' }];
const statusStyles: Record<TimelineStatus, string> = { completed: 'border-emerald-100 bg-emerald-50 text-emerald-800', in_progress: 'border-rose-200 bg-rose-50 text-rose-800 shadow-md shadow-rose-100/80', planned: 'border-sky-100 bg-sky-50 text-sky-800', unplanned: 'border-slate-200 bg-slate-50 text-slate-500' };

function Icon({ name }: { name: 'search' | 'filter' | 'calendar' | 'close' }) {
  const paths = { search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, filter: <path d="M4 6h16M7 12h10m-7 6h4"/>, calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>, close: <path d="m6 6 12 12M18 6 6 18"/> };
  return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-4 w-4" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">{paths[name]}</svg>;
}

function TrackTitle({ index, title, subtitle }: { index: string; title: string; subtitle: string }) { return <div className="w-36 shrink-0 pr-5"><span className="text-[10px] font-bold tracking-[0.18em] text-[#ef233c]">{index}</span><h3 className="mt-1 text-sm font-bold text-slate-800">{title}</h3><p className="mt-1 text-[11px] leading-4 text-slate-400">{subtitle}</p></div> }

function LifeStageTrack({ onSelect }: { onSelect: (item: TimelineItem) => void }) { return <div className="flex min-h-32 border-b border-slate-100 py-5"><TrackTitle index="01 / MACRO" title="人生阶段" subtitle="人生的长期坐标"/><div className="relative flex flex-1 items-center"><div className="absolute left-2 right-2 top-1/2 h-px bg-slate-200" />{lifeStages.map((item) => <button type="button" key={item.id} onClick={() => onSelect(item)} className="group relative z-10 flex flex-1 flex-col items-center text-center"><span className={`h-3 w-3 rounded-full border-2 border-white transition group-hover:scale-150 ${item.status === 'completed' ? 'bg-emerald-400' : item.status === 'in_progress' ? 'bg-[#ef233c] ring-4 ring-rose-100' : 'bg-slate-300'}`} /><strong className="mt-3 whitespace-nowrap text-[11px] text-slate-700 group-hover:text-[#ef233c]">{item.title}</strong><span className="mt-1 text-[9px] text-slate-400">{item.subtitle}</span></button>)}</div></div> }

function CardTrack({ index, title, subtitle, items, purple, onSelect }: { index: string; title: string; subtitle: string; items: TimelineItem[]; purple?: boolean; onSelect: (item: TimelineItem) => void }) { return <div className="flex min-h-36 border-b border-slate-100 py-5"><TrackTitle index={index} title={title} subtitle={subtitle}/><div className="grid flex-1 grid-cols-6 items-center gap-2">{items.map((item) => <button title={item.description} type="button" onClick={() => onSelect(item)} key={item.id} className={`interactive-fade min-h-20 rounded-2xl border p-3 text-left hover:-translate-y-1 hover:shadow-lg ${purple ? item.status === 'in_progress' ? 'border-violet-200 bg-violet-100 text-violet-900 shadow-md shadow-violet-100' : 'border-violet-100 bg-violet-50/70 text-violet-700' : statusStyles[item.status]}`}><div className="flex items-start justify-between gap-1"><span className="line-clamp-2 text-[11px] font-bold leading-4">{item.title}</span>{item.priority && item.priority >= 9 ? <span className="h-1.5 w-1.5 shrink-0 rounded-full bg-[#ef233c]"/> : null}</div><p className="mt-2 text-[9px] opacity-65">{item.subtitle}</p></button>)}</div></div> }

function weekDays(tasks: Task[]) {
  const now = new Date(); const day = now.getDay() || 7; const monday = new Date(now); monday.setDate(now.getDate() - day + 1);
  const fallback = ['阅读论文 2 篇', '实验记录整理', '英语学习', '组会汇报', '跑步 5km', '复盘日记', '论文初稿撰写'];
  return Array.from({ length: 7 }, (_, index) => { const date = new Date(monday); date.setDate(monday.getDate() + index); const key = date.toISOString().slice(0, 10); const matched = tasks.filter((task) => task.deadline?.slice(0, 10) === key).slice(0, 2); return { key, date, isToday: date.toDateString() === now.toDateString(), tasks: matched.length ? matched.map((task) => ({ title: task.title, done: task.lifecycleStatus === 'completed' })) : [{ title: fallback[index], done: index < day - 1 }, { title: index % 2 ? '早睡' : '代码实现', done: false }] }; });
}

function WeeklyTrack({ tasks, onSelect }: { tasks: Task[]; onSelect: (item: TimelineItem) => void }) { const days = weekDays(tasks); return <div className="flex min-h-52 py-5"><TrackTitle index="04 / ACTION" title="本周执行" subtitle="目标最终落到今天"/><div className="grid flex-1 grid-cols-7 gap-2">{days.map((day) => <div key={day.key} className={`rounded-2xl border p-2 ${day.isToday ? 'border-rose-300 bg-rose-50/80 shadow-lg shadow-rose-100' : 'border-slate-100 bg-slate-50/60'}`}><div className={`rounded-xl px-2 py-2 ${day.isToday ? 'bg-[#ef233c] text-white' : 'text-slate-500'}`}><p className="text-[9px] font-semibold">{day.date.toLocaleDateString('zh-CN', { weekday: 'short' })}</p><p className="mt-0.5 text-sm font-bold">{day.date.getMonth() + 1}/{day.date.getDate()}</p>{day.isToday ? <p className="mt-1 text-[8px] font-bold tracking-widest">TODAY</p> : null}</div><div className="mt-2 space-y-1.5">{day.tasks.map((task, index) => <button type="button" onClick={() => onSelect({ id: `${day.key}-${index}`, type: 'task', title: task.title, startDate: day.key, status: task.done ? 'completed' : day.isToday ? 'in_progress' : 'planned', description: `安排在 ${day.key} 的执行任务` })} key={`${task.title}-${index}`} className={`block w-full rounded-lg border px-2 py-2 text-left text-[9px] leading-3 transition hover:-translate-y-0.5 hover:shadow ${task.done ? 'border-emerald-100 bg-emerald-50 text-emerald-700 line-through' : day.isToday ? 'border-rose-100 bg-white font-semibold text-slate-800' : 'border-white bg-white text-slate-600'}`}>{task.title}</button>)}</div></div>)}</div></div> }

export function LifeTimelineSection({ goals, tasks }: Props) {
  const [zoom, setZoom] = useState<TimelineZoom>('life'); const [selected, setSelected] = useState<TimelineItem>(); const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(''); const [filterActive, setFilterActive] = useState(false);
  const goalItems = useMemo(() => goals.slice(0, 2).map((goal): TimelineItem => ({ id: `goal-${goal.id}`, type: 'annual_goal', title: goal.title, subtitle: goal.targetDate?.slice(0, 4) || '长期', startDate: goal.targetDate || '', status: 'in_progress', priority: goal.priority })), [goals]);
  const shownGoals = [...annualGoals.slice(0, Math.max(4, 6 - goalItems.length)), ...goalItems].filter((item) => !filterActive || item.status === 'in_progress').filter((item) => !query || item.title.toLowerCase().includes(query.toLowerCase())).slice(0, 6);
  const showMacro = zoom === 'life' || zoom === 'decade'; const showGoals = !['week', 'day'].includes(zoom); const showProjects = !['life', 'day'].includes(zoom);
  const milestones = weekDays(tasks).flatMap((day) => day.tasks.slice(0, 1).map((task) => ({ title: task.title, date: `${day.date.getMonth() + 1}月${day.date.getDate()}日` }))).slice(0, 3);
  return <section className="overflow-hidden rounded-[2rem] border border-white/80 bg-[#f7f8fa] shadow-xl shadow-slate-200/50">
    <header className="flex flex-col gap-5 border-b border-slate-200/70 bg-white/90 p-6 lg:flex-row lg:items-center lg:justify-between">
      <div><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#ef233c] ring-4 ring-rose-100"/><p className="text-xs font-bold tracking-[0.2em] text-[#ef233c]">LIFE COORDINATE SYSTEM</p></div><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950">人生时间坐标轴</h1><p className="mt-2 text-sm text-slate-500">把人生规划可视化，让每一步都有方向</p></div>
      <div className="flex flex-wrap items-center gap-2">{searchOpen ? <input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索目标…" className="w-36 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs outline-none focus:border-rose-300"/> : null}<button aria-label="搜索" onClick={() => setSearchOpen(!searchOpen)} className="grid h-9 w-9 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500 hover:border-rose-200 hover:text-[#ef233c]"><Icon name="search"/></button><button aria-pressed={filterActive} onClick={() => setFilterActive(!filterActive)} className={`flex h-9 items-center gap-2 rounded-xl border px-3 text-xs font-semibold ${filterActive ? 'border-rose-200 bg-rose-50 text-[#ef233c]' : 'border-slate-200 bg-white text-slate-500'}`}><Icon name="filter"/>进行中</button><button onClick={() => setZoom('week')} className="flex h-9 items-center gap-2 rounded-xl bg-[#ef233c] px-3 text-xs font-bold text-white shadow-md shadow-rose-200"><Icon name="calendar"/>今天</button></div>
    </header>
    <div className="grid gap-5 p-4 md:p-6 xl:grid-cols-[minmax(0,1fr)_220px]">
      <div className="min-w-0 overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="overflow-x-auto"><div className="relative min-w-[900px] px-5">
        <div className="pointer-events-none absolute bottom-5 left-[49%] top-3 z-20 w-px bg-[#ef233c]/70"><span className="absolute -left-[23px] top-0 rounded-full bg-[#ef233c] px-2 py-1 text-[9px] font-bold tracking-wider text-white shadow-md shadow-rose-200">现在</span><span className="absolute -left-1 bottom-0 h-2 w-2 rounded-full bg-[#ef233c]"/></div>
        {showMacro ? <LifeStageTrack onSelect={setSelected}/> : null}{showGoals ? <CardTrack index="02 / GOALS" title="年度目标" subtitle="关键成果与里程碑" items={shownGoals} onSelect={setSelected}/> : null}{showProjects ? <CardTrack index="03 / PROJECT" title="学期 / 项目" subtitle="连接战略与行动" items={projects} purple onSelect={setSelected}/> : null}<WeeklyTrack tasks={tasks} onSelect={setSelected}/>
      </div></div><footer className="flex flex-col gap-3 border-t border-slate-100 bg-slate-50/70 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-3 text-[10px] text-slate-500">{Object.entries(statusLabels).map(([status, label]) => <span key={status} className="flex items-center gap-1.5"><i className={`h-2 w-2 rounded-full ${status === 'completed' ? 'bg-emerald-400' : status === 'in_progress' ? 'bg-[#ef233c]' : status === 'planned' ? 'bg-sky-400' : 'bg-slate-300'}`}/>{label}</span>)}</div><div className="flex rounded-xl border border-slate-200 bg-white p-1">{zooms.map((item) => <button key={item.id} onClick={() => setZoom(item.id)} className={`rounded-lg px-2.5 py-1.5 text-[10px] font-semibold transition ${zoom === item.id ? 'bg-slate-900 text-white shadow-sm' : 'text-slate-400 hover:text-slate-700'}`}>{item.label}</button>)}</div></footer></div>
      <TimelineSidebar weekMilestones={milestones} longTermGoals={[{ title: '成为有影响力的研究者', date: '2032' }, { title: '数字生命模型', date: '2030+' }, { title: '帮助更多人规划人生', date: '2040+' }]} onSelect={setSelected}/>
    </div>
    {selected ? <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/25 p-4 backdrop-blur-sm sm:items-center" onMouseDown={(e) => { if (e.target === e.currentTarget) setSelected(undefined); }}><article role="dialog" aria-modal="true" aria-labelledby="timeline-detail-title" className="w-full max-w-md rounded-[1.75rem] bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><span className={`inline-flex rounded-full border px-2.5 py-1 text-[10px] font-bold ${statusStyles[selected.status]}`}>{statusLabels[selected.status]}</span><h2 id="timeline-detail-title" className="mt-4 text-2xl font-bold text-slate-950">{selected.title}</h2><p className="mt-2 text-xs text-slate-400">{selected.subtitle || selected.startDate}{selected.endDate ? ` — ${selected.endDate}` : ''}</p></div><button aria-label="关闭详情" onClick={() => setSelected(undefined)} className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-slate-500 hover:bg-rose-50 hover:text-[#ef233c]"><Icon name="close"/></button></div><p className="mt-6 rounded-2xl bg-slate-50 p-4 text-sm leading-7 text-slate-600">{selected.description || '这是人生坐标轴上的一个关键节点。未来可在此连接目标、任务、复盘与提醒。'}</p>{selected.priority ? <div className="mt-5"><div className="flex justify-between text-xs font-semibold text-slate-500"><span>优先级</span><span>{selected.priority}/10</span></div><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#ef233c]" style={{ width: `${selected.priority * 10}%` }}/></div></div> : null}</article></div> : null}
  </section>;
}

