import type { ActivityType, Importance } from '../../types/task.js';
import type { CaptureInput, CaptureInterpretation, CaptureTaskDraft } from './types.js';
export class CaptureParseError extends Error { constructor(message: string) { super(message); this.name = 'CaptureParseError'; } }
const categories: ActivityType[] = ['task','schedule','entertainment','recovery','study','research','fitness','exercise','work','life','social','other'];
const cap = (value: unknown, max: number) => typeof value === 'string' ? value.trim().slice(0, max) : '';
const importance = (value: unknown): Importance => Math.max(1, Math.min(10, Math.round(Number(value) || 5))) as Importance;
const date = (value: unknown) => { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}(?:T[^\s]+)?$/.test(value)) return undefined; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) || (value.length === 10 && parsed.toISOString().slice(0,10) !== value) ? undefined : value; };
const refs = (value: unknown, valid: Set<string>) => Array.isArray(value) ? value.filter((ref): ref is string => typeof ref === 'string' && (ref === 'capture:text' || ref.startsWith('asset:') || ref.startsWith('url:') || ref.startsWith('audio:')) && (ref === 'capture:text' || [...valid].some((source) => ref === source))).slice(0, 20) : [];
const confidence = (value: unknown) => typeof value === 'number' && value >= 0 && value <= 1 ? value : undefined;
const list = (raw: Record<string, unknown>, field: string, max: number) => Array.isArray(raw[field]) ? raw[field].slice(0, max) : [];
export function parseCaptureInterpretation(response: string, capture?: CaptureInput): CaptureInterpretation {
  let raw: Record<string, unknown>; try { raw = JSON.parse(response.replace(/^```(?:json)?\s*|\s*```$/g, '')); } catch { throw new CaptureParseError('AI 返回的 JSON 无法解析，请重试。'); }
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new CaptureParseError('AI 返回结构无效，请重试。');
  const sourceIds = new Set<string>(['capture:text', ...(capture?.assets.map((asset) => `asset:${asset.id}`) ?? []), ...(capture?.links.map((_, index) => `url:${index}`) ?? [])]);
  const parseItems = (field: string, max: number, prefix: string) => list(raw, field, max).map((item, index) => { const value = item as Record<string, unknown>; return { value, itemId: cap(value.id, 80) || `${prefix}-${index + 1}` }; });
  const seen = new Set<string>(); const unique = (id: string) => { if (seen.has(id)) throw new CaptureParseError(`重复的草稿 ID：${id}`); seen.add(id); };
  const goals = parseItems('goals', 20, 'goal').map(({ value, itemId }) => { unique(itemId); const title = cap(value.title, 240); if (!title) return undefined; return { id: itemId, title, targetDate: date(value.targetDate), category: categories.includes(value.category as ActivityType) ? value.category as ActivityType : 'task', priority: importance(value.priority), included: true, confidence: confidence(value.confidence), sourceRefs: refs(value.sourceRefs, sourceIds) }; }).filter(Boolean) as CaptureInterpretation['goals'];
  const goalIds = new Set(goals.map((goal) => goal.id)); const warnings: string[] = [];
  const tasks = parseItems('tasks', 100, 'task').map(({ value, itemId }) => { unique(itemId); const title = cap(value.title, 240); if (!title) return undefined; const minutes = Number(value.estimatedDuration); const goalDraftId = typeof value.goalDraftId === 'string' && goalIds.has(value.goalDraftId) ? value.goalDraftId : undefined; if (value.goalDraftId && !goalDraftId) warnings.push(`任务“${title}”引用了不存在的目标，已暂不关联。`); const deps = Array.isArray(value.dependencyDraftIds) ? value.dependencyDraftIds.filter((dep): dep is string => typeof dep === 'string').slice(0, 20) : []; return { id: itemId, title, description: cap(value.description, 2000) || undefined, importance: importance(value.importance), deadline: date(value.deadline), estimatedDuration: Number.isFinite(minutes) && minutes > 0 && minutes <= 10080 ? Math.round(minutes) : undefined, category: categories.includes(value.category as ActivityType) ? value.category as ActivityType : 'task', goalDraftId, dependencyDraftIds: deps, included: true, confidence: confidence(value.confidence), sourceRefs: refs(value.sourceRefs, sourceIds) } satisfies CaptureTaskDraft; }).filter(Boolean) as CaptureTaskDraft[];
  const taskIds = new Set(tasks.map((task) => task.id)); const cyclic = new Set<string>(); const visiting = new Set<string>(); const byId = new Map(tasks.map((task) => [task.id, task]));
  const visit = (task: CaptureTaskDraft) => { if (visiting.has(task.id)) { cyclic.add(task.id); return; } visiting.add(task.id); task.dependencyDraftIds = task.dependencyDraftIds.filter((dep) => { if (dep === task.id || !taskIds.has(dep)) { warnings.push(`任务“${task.title}”存在无效依赖，已移除。`); return false; } return true; }); task.dependencyDraftIds.forEach((dep) => { const target = byId.get(dep); if (target) { visit(target); if (cyclic.has(target.id)) cyclic.add(task.id); } }); visiting.delete(task.id); };
  tasks.forEach(visit); tasks.forEach((task) => { if (cyclic.has(task.id)) { task.dependencyDraftIds = []; warnings.push(`任务“${task.title}”存在循环依赖，已移除。`); } });
  const commitments = parseItems('commitments', 50, 'commitment').map(({ value, itemId }) => { unique(itemId); const title = cap(value.title, 240); return title ? { id: itemId, title, date: date(value.date), included: true, confidence: confidence(value.confidence), sourceRefs: refs(value.sourceRefs, sourceIds) } : undefined; }).filter(Boolean) as CaptureInterpretation['commitments'];
  const context = parseItems('context', 50, 'context').map(({ value, itemId }) => { unique(itemId); const text = cap(value.text, 2000); return text ? { id: itemId, text, confidence: confidence(value.confidence), sourceRefs: refs(value.sourceRefs, sourceIds) } : undefined; }).filter(Boolean) as CaptureInterpretation['context'];
  const ambiguities = list(raw, 'ambiguities', 50).filter((value): value is string => typeof value === 'string').map((value, index) => ({ id: `ambiguity-${index + 1}`, text: cap(value, 500) })).filter((item) => item.text);
  const notes = list(raw, 'notes', 20).filter((value): value is string => typeof value === 'string').map((value) => cap(value, 500)).filter(Boolean); return { goals, tasks, commitments, context, ambiguities, notes: [...warnings, ...notes].slice(0, 20) };
}
