import { useEffect, useState } from 'react';
import { interpretCapture } from '../domain/capture/interpreter';
import type { CaptureInput, CaptureInterpretation, CaptureState } from '../domain/capture/types';
import type { AISettings } from '../services/aiClient';
import type { Goal, Task } from '../types/task';
import { supabase } from '../lib/supabaseClient';
import { MultimodalComposer } from './MultimodalComposer';

interface Props { ownerUserId: string; settings: AISettings; tasks: Task[]; goals: Goal[]; initialCapture?: CaptureInput; onConfirm: (capture: CaptureInput, interpretation: CaptureInterpretation, model?: string) => Promise<void>; onCancelInitial?: (captureId: string) => void; }

export function CaptureIntakePanel({ ownerUserId, settings, tasks, goals, initialCapture, onConfirm, onCancelInitial }: Props) {
  const [state, setState] = useState<CaptureState>('idle'); const [capture, setCapture] = useState<CaptureInput | undefined>(initialCapture); const [review, setReview] = useState<CaptureInterpretation>(); const [model, setModel] = useState<string>(); const [error, setError] = useState<string>();
  useEffect(() => { if (initialCapture?.ownerKey === `user:${ownerUserId}`) { setCapture(initialCapture); setState('capturing'); } }, [initialCapture, ownerUserId]);
  async function submit(intake: import('../types/intake').MultimodalIntake) {
    setState('interpreting'); setError(undefined);
    const active = capture?.id === intake.intakeId ? capture : { id: intake.intakeId, ownerKey: `user:${ownerUserId}` as const, text: intake.text, links: intake.links ?? [], assets: intake.assets.map((asset, index) => ({ id: `asset-${index}`, kind: asset.kind === 'document' ? 'document' as const : asset.kind, name: asset.fileName, mimeType: asset.mimeType, size: asset.size, storagePath: asset.storagePath, status: 'metadata_only' as const })) };
    try {
      if (intake.assets.length) {
        const session = await supabase.auth.getSession();
        if (!session?.access_token || session.user?.id !== ownerUserId) throw new Error('登录状态已变化，请重新开始本次整理。');
        const response = await fetch('/api/intake', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(intake) });
        if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || '附件处理请求失败。');
      }
      const result = await interpretCapture(settings, active, tasks, goals, new Date(), Intl.DateTimeFormat().resolvedOptions().timeZone); setCapture(active); setReview(result.interpretation); setModel(result.model); setState('review');
    } catch (cause) { setError(cause instanceof Error ? cause.message : '解释失败'); setState('error'); }
  }
  if (state === 'review' && review && capture) return <section className="rounded-[1.5rem] border border-sky-100 bg-sky-50/50 p-5" data-testid="capture-review"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold text-slate-900">确认这次整理</p><p className="mt-1 text-xs text-slate-500">仅在确认后写入你的任务与目标。标题可直接修改；不需要的项可排除。</p></div><button type="button" className="text-sm text-slate-500" onClick={() => { setReview(undefined); setState('capturing'); }}>继续编辑输入</button></div><div className="mt-4 grid gap-3"><DraftList title="目标" entries={review.goals} onToggle={(id) => setReview({ ...review, goals: review.goals.map((item) => item.id === id ? { ...item, included: !item.included } : item) })} onTitle={(id, title) => setReview({ ...review, goals: review.goals.map((item) => item.id === id ? { ...item, title } : item) })} /><DraftList title="任务" entries={review.tasks} onToggle={(id) => setReview({ ...review, tasks: review.tasks.map((item) => item.id === id ? { ...item, included: !item.included } : item) })} onTitle={(id, title) => setReview({ ...review, tasks: review.tasks.map((item) => item.id === id ? { ...item, title } : item) })} /><DraftList title="固定承诺（保留供你核对，不会自动创建任务）" entries={review.commitments} onToggle={(id) => setReview({ ...review, commitments: review.commitments.map((item) => item.id === id ? { ...item, included: !item.included } : item) })} onTitle={(id, title) => setReview({ ...review, commitments: review.commitments.map((item) => item.id === id ? { ...item, title } : item) })} />{review.context.length ? <DraftList title="背景与已完成事实" entries={review.context.map((item) => ({ ...item, title: item.text, included: false }))} /> : null}{review.ambiguities.length ? <ul className="rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{review.ambiguities.map((item) => <li key={item.id}>{item.text}</li>)}</ul> : null}</div><div className="mt-5 flex gap-3"><button type="button" onClick={() => void (async () => { setState('materializing'); try { await onConfirm(capture, review, model); setState('completed'); } catch (cause) { setError(cause instanceof Error ? cause.message : '写入失败'); setState('error'); } })()} className="rounded-full bg-slate-900 px-5 py-2 text-sm font-semibold text-white">确认并保存</button><button type="button" onClick={() => { onCancelInitial?.(capture.id); setCapture(undefined); setReview(undefined); setState('idle'); }} className="text-sm text-slate-500">取消</button></div></section>;
  return <section className="rounded-[1.5rem] border border-slate-200 bg-white/80 p-5" data-testid="capture-intake"><div className="mb-3"><p className="text-sm font-semibold text-slate-900">说说你现在想推进什么</p><p className="mt-1 text-sm text-slate-500">可以一次写下多个项目、任务、约定和背景；整理后由你确认。</p>{capture?.assets.some((asset) => asset.status === 'needs_reattach') ? <p className="mt-2 text-xs text-amber-700">刷新后附件需要重新添加；已保留文字、链接和文件信息。</p> : null}</div><MultimodalComposer disabled={state === 'interpreting' || state === 'materializing'} initialCapture={capture} onSubmit={submit} placeholder="例如：整理毕业计划、下周与客户开会、已经买好车票…" />{state === 'interpreting' || state === 'materializing' ? <p className="mt-3 text-sm text-sky-700">{state === 'interpreting' ? '正在整理，尚未写入工作区…' : '正在保存你的确认…'}</p> : null}{error ? <p className="mt-3 text-sm text-rose-600">{error}</p> : null}</section>;
}
function DraftList({ title, entries, onToggle, onTitle }: { title: string; entries: Array<{ id: string; title: string; included: boolean }>; onToggle?: (id: string) => void; onTitle?: (id: string, title: string) => void }) { return <div><p className="mb-1 text-xs font-semibold text-slate-500">{title}</p><ul className="space-y-1">{entries.map((entry) => <li key={entry.id} className="flex items-center gap-2 rounded-lg bg-white px-3 py-2 text-sm text-slate-700">{onToggle ? <input type="checkbox" checked={entry.included} onChange={() => onToggle(entry.id)} /> : null}{onTitle ? <input aria-label={`${title}标题`} value={entry.title} onChange={(event) => onTitle(entry.id, event.target.value)} className="min-w-0 flex-1 bg-transparent outline-none" /> : <span>{entry.title}</span>}</li>)}</ul></div>; }
