import { useEffect, useState } from 'react';
import { interpretCapture } from '../domain/capture/interpreter';
import { validateCaptureReview } from '../domain/capture/review';
import type { CaptureGoalDraft, CaptureInput, CaptureInterpretation, CaptureState, CaptureTaskDraft } from '../domain/capture/types';
import { supabase } from '../lib/supabaseClient';
import type { AISettings } from '../services/aiClient';
import type { ActivityType, Goal, Importance, Task } from '../types/task';
import { MultimodalComposer } from './MultimodalComposer';

const categories: ActivityType[] = ['task','schedule','entertainment','recovery','study','research','fitness','exercise','work','life','social','other'];
interface Props { ownerUserId: string; settings: AISettings; tasks: Task[]; goals: Goal[]; initialCapture?: CaptureInput; onConfirm: (capture: CaptureInput, interpretation: CaptureInterpretation, model?: string) => Promise<void>; onCancelInitial?: (captureId: string) => void; }
export function CaptureIntakePanel({ ownerUserId, settings, tasks, goals, initialCapture, onConfirm, onCancelInitial }: Props) {
  const [state, setState] = useState<CaptureState>('idle'); const [capture, setCapture] = useState<CaptureInput | undefined>(initialCapture); const [review, setReview] = useState<CaptureInterpretation>(); const [model, setModel] = useState<string>(); const [error, setError] = useState<string>();
  useEffect(() => { if (initialCapture?.ownerKey === `user:${ownerUserId}`) { setCapture(initialCapture); setState('capturing'); } }, [initialCapture, ownerUserId]);
  async function submit(intake: import('../types/intake').MultimodalIntake): Promise<boolean> { setState('interpreting'); setError(undefined); const uploaded = intake.assets.map((asset, index) => ({ id: `asset-${index}`, kind: asset.kind, name: asset.fileName, mimeType: asset.mimeType, size: asset.size, storagePath: asset.storagePath, availability: 'available' as const, semanticCoverage: 'metadata_only' as const })); const active = capture?.id === intake.intakeId ? { ...capture, text: intake.text, links: intake.links ?? capture.links, assets: [...capture.assets.filter((asset) => asset.availability === 'needs_reattach'), ...uploaded] } : { id: intake.intakeId, ownerKey: `user:${ownerUserId}` as const, text: intake.text, links: intake.links ?? [], assets: uploaded }; try { if (intake.assets.length) { const session = await supabase.auth.getSession(); if (!session?.access_token || session.user?.id !== ownerUserId) throw new Error('登录状态已变化，请重新开始本次整理。'); const response = await fetch('/api/intake', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(intake) }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.error || '附件处理请求失败。'); } const result = await interpretCapture(settings, active, tasks, goals, new Date(), Intl.DateTimeFormat().resolvedOptions().timeZone); const duplicateTitles = new Set(tasks.map((task) => task.title.trim().toLocaleLowerCase())); result.interpretation.tasks = result.interpretation.tasks.map((task) => duplicateTitles.has(task.title.toLocaleLowerCase()) ? { ...task, included: false } : task); setCapture(active); setReview(result.interpretation); setModel(result.model); setState('review'); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : '解释失败'); setState('error'); return false; } }
  function addTask() { if (!review) return; setReview({ ...review, tasks: [...review.tasks, { id: `manual-${crypto.randomUUID()}`, title: '', importance: 5, category: 'task', dependencyDraftIds: [], included: true, sourceRefs: ['manual:review'] }] }); }
  async function confirm() { if (!review || !capture) return; const errors = validateCaptureReview(review); if (errors.length) { setError(errors.join(' ')); return; } setState('materializing'); try { await onConfirm(capture, review, model); setCapture(undefined); setReview(undefined); setError(undefined); setModel(undefined); setState('idle'); } catch (cause) { setError(cause instanceof Error ? cause.message : '写入失败'); setState('review'); } }
  function cancel() { if (capture) onCancelInitial?.(capture.id); setCapture(undefined); setReview(undefined); setError(undefined); setModel(undefined); setState('idle'); }
  if (state === 'review' && review && capture) return <section className="rounded-3xl border border-sky-100 bg-sky-50/50 p-5" data-testid="capture-review"><header><h2 className="font-semibold">确认这次整理</h2><p className="text-xs text-slate-500">包含 {review.goals.filter((x) => x.included).length + review.tasks.filter((x) => x.included).length} 项，排除 {review.goals.filter((x) => !x.included).length + review.tasks.filter((x) => !x.included).length} 项</p></header>{review.notes.length ? <ul className="mt-3 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">{review.notes.map((note) => <li key={note}>{note}</li>)}</ul> : null}<div className="mt-4 space-y-3"><p className="text-xs font-semibold text-slate-500">目标</p>{review.goals.map((goal) => <GoalEditor key={goal.id} goal={goal} onChange={(next) => setReview({ ...review, goals: review.goals.map((item) => item.id === goal.id ? next : item) })} />)}<div className="flex items-center justify-between"><p className="text-xs font-semibold text-slate-500">任务</p><button type="button" onClick={addTask} className="text-sm font-semibold text-sky-700">＋ 添加任务</button></div>{review.tasks.map((task) => <TaskEditor key={task.id} task={task} allTasks={review.tasks} goals={review.goals} duplicate={tasks.some((existing) => existing.title.trim().toLocaleLowerCase() === task.title.trim().toLocaleLowerCase())} onChange={(next) => setReview({ ...review, tasks: review.tasks.map((item) => item.id === task.id ? next : item) })} />)}<ReviewOnlySections interpretation={review} /></div>{error ? <p className="mt-3 text-sm text-rose-600">{error}</p> : null}<div className="mt-5 flex gap-3"><button type="button" onClick={() => void confirm()} className="rounded-full bg-slate-900 px-5 py-2 text-sm font-semibold text-white">确认并保存</button><button type="button" onClick={cancel} className="text-sm text-slate-500">取消</button></div></section>;
  return <section className="rounded-3xl border border-slate-200 bg-white/80 p-5" data-testid="capture-intake"><h2 className="font-semibold">说说你现在想推进什么</h2><p className="mb-3 text-sm text-slate-500">可以一次写下多个项目、任务、约定和背景；整理后由你确认。</p>{capture?.assets.filter((asset) => asset.availability === 'needs_reattach').map((asset) => <div key={asset.id} className="mb-2 flex justify-between rounded-lg bg-amber-50 p-2 text-xs text-amber-800"><span>{asset.name} · {asset.mimeType || '未知类型'} · {asset.size ? `${Math.round(asset.size / 1024)} KB` : '大小未知'} · 需要重新添加</span><button type="button" onClick={() => setCapture((current) => current ? { ...current, assets: current.assets.filter((item) => item.id !== asset.id) } : current)}>移除</button></div>)}<MultimodalComposer disabled={state === 'interpreting' || state === 'materializing'} initialCapture={capture} onSubmit={submit} />{error ? <p className="mt-3 text-sm text-rose-600">{error}</p> : null}</section>;
}
const clamp = (value: number) => Math.max(1, Math.min(10, Math.round(value || 5))) as Importance;
function ReviewOnlySections({ interpretation }: { interpretation: CaptureInterpretation }) {
  return <div className="space-y-3 pt-1">
    {interpretation.commitments.length ? <section className="rounded-xl bg-white p-3" data-testid="capture-review-commitments"><p className="text-xs font-semibold text-slate-500">约定</p><p className="mt-1 text-xs text-slate-400">仅供确认，不会自动保存。</p><ul className="mt-2 space-y-1 text-sm text-slate-700">{interpretation.commitments.map((item) => <li key={item.id}>{item.title}{item.date ? ` · ${item.date}` : ''}</li>)}</ul></section> : null}
    {interpretation.context.length ? <section className="rounded-xl bg-white p-3" data-testid="capture-review-context"><p className="text-xs font-semibold text-slate-500">背景与已完成事实</p><p className="mt-1 text-xs text-slate-400">非行动信息，不会创建任务。</p><ul className="mt-2 space-y-1 text-sm text-slate-700">{interpretation.context.map((item) => <li key={item.id}>{item.text}</li>)}</ul></section> : null}
    {interpretation.ambiguities.length ? <section className="rounded-xl border border-amber-200 bg-amber-50 p-3" data-testid="capture-review-ambiguities"><p className="text-xs font-semibold text-amber-800">需要留意</p><p className="mt-1 text-xs text-amber-700">请在确认前处理或核对这些问题。</p><ul className="mt-2 space-y-1 text-sm text-amber-900">{interpretation.ambiguities.map((item) => <li key={item.id}>{item.text}</li>)}</ul></section> : null}
  </div>;
}
function GoalEditor({ goal, onChange }: { goal: CaptureGoalDraft; onChange: (goal: CaptureGoalDraft) => void }) { return <details open className="rounded-xl bg-white p-3"><summary className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={goal.included} onChange={(e) => onChange({ ...goal, included: e.target.checked })} onClick={(e) => e.stopPropagation()} /><span>{goal.title || '未命名目标'}</span></summary><div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label="目标标题" value={goal.title} onChange={(e) => onChange({ ...goal, title: e.target.value })} className="rounded-lg border p-2" /><input aria-label="目标优先级" type="number" min="1" max="10" value={goal.priority} onChange={(e) => onChange({ ...goal, priority: clamp(Number(e.target.value)) })} className="rounded-lg border p-2" /><input aria-label="目标日期" type="date" value={goal.targetDate ?? ''} onChange={(e) => onChange({ ...goal, targetDate: e.target.value || undefined })} className="rounded-lg border p-2" /><select aria-label="目标分类" value={goal.category} onChange={(e) => onChange({ ...goal, category: e.target.value as ActivityType })} className="rounded-lg border p-2">{categories.map((value) => <option key={value}>{value}</option>)}</select></div>{goal.confidence !== undefined && goal.confidence < .7 ? <p className="mt-2 text-xs text-amber-700">重要性或日期为 AI 推断，可修改</p> : null}</details>; }
function TaskEditor({ task, allTasks, goals, duplicate, onChange }: { task: CaptureTaskDraft; allTasks: CaptureTaskDraft[]; goals: CaptureGoalDraft[]; duplicate: boolean; onChange: (task: CaptureTaskDraft) => void }) { return <details open className="rounded-xl bg-white p-3"><summary className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={task.included} onChange={(e) => onChange({ ...task, included: e.target.checked })} onClick={(e) => e.stopPropagation()} /><span>{task.title || '未命名任务'}</span></summary>{duplicate ? <p className="mt-2 text-xs text-amber-700">可能与现有任务重复：“{task.title}”（默认排除，可明确重新包含）</p> : null}<div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label="任务标题" value={task.title} onChange={(e) => onChange({ ...task, title: e.target.value })} className="rounded-lg border p-2" /><input aria-label="任务重要性" type="number" min="1" max="10" value={task.importance} onChange={(e) => onChange({ ...task, importance: clamp(Number(e.target.value)) })} className="rounded-lg border p-2" /><textarea aria-label="任务描述" value={task.description ?? ''} onChange={(e) => onChange({ ...task, description: e.target.value || undefined })} className="rounded-lg border p-2" /><input aria-label="任务截止日期" type="date" value={task.deadline ?? ''} onChange={(e) => onChange({ ...task, deadline: e.target.value || undefined })} className="rounded-lg border p-2" /><input aria-label="预计分钟" type="number" min="1" value={task.estimatedDuration ?? ''} onChange={(e) => onChange({ ...task, estimatedDuration: e.target.value ? Number(e.target.value) : undefined })} className="rounded-lg border p-2" /><select aria-label="任务分类" value={task.category} onChange={(e) => onChange({ ...task, category: e.target.value as ActivityType })} className="rounded-lg border p-2">{categories.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="关联目标" value={task.goalDraftId ?? ''} onChange={(e) => onChange({ ...task, goalDraftId: e.target.value || undefined })} className="rounded-lg border p-2"><option value="">独立任务 / 无目标</option>{goals.filter((goal) => goal.included).map((goal) => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></div>{task.dependencyDraftIds.length ? <div className="mt-2 flex flex-wrap gap-2">{task.dependencyDraftIds.map((id) => <button key={id} type="button" onClick={() => onChange({ ...task, dependencyDraftIds: task.dependencyDraftIds.filter((value) => value !== id) })} className="rounded-full bg-slate-100 px-2 py-1 text-xs">依赖：{allTasks.find((item) => item.id === id)?.title || '无效任务'} ×</button>)}</div> : null}{task.confidence !== undefined && task.confidence < .7 ? <p className="mt-2 text-xs text-amber-700">重要性、截止时间或目标关联为 AI 推断，请确认</p> : null}</details>; }
