import type { ReactNode } from 'react';
import type { VDNotification } from '../types/notification';
import type { UserProfile } from '../types/task';

const pages = [
  ['/app', '现在'], ['/app/tasks', '任务'], ['/app/plan', '计划'], ['/app/ops', '执行'], ['/app/review', '回顾'],
] as const;

export function V2AppShell({ path, children, onNavigate, onSignOut, profile, notifications }: { path: string; children: ReactNode; onNavigate: (path: string) => void; onSignOut: () => void; profile: UserProfile; notifications: VDNotification[] }) {
  const unread = notifications.some((notification) => !notification.isRead);
  const avatarInitial = (profile.nickname || profile.username || 'VD').slice(0, 1).toUpperCase();
  return <div className="min-h-screen bg-[#fafafa] text-zinc-900">
    <aside className="fixed inset-y-0 left-0 hidden w-56 border-r border-zinc-200 bg-white px-4 py-5 lg:flex lg:flex-col"><button type="button" onClick={() => onNavigate('/app')} className="flex items-center gap-2.5 px-2 text-left text-base font-semibold"><img src="/logo.png" alt="Visual Deadline" className="h-8 w-8 object-contain" />Visual Deadline</button><nav className="mt-10 space-y-1" aria-label="主导航"><span className="px-2 text-[11px] font-semibold tracking-[.16em] text-zinc-400">工作区</span>{pages.map(([href, label]) => <button key={href} type="button" onClick={() => onNavigate(href)} aria-current={path === href ? 'page' : undefined} className={`mt-1 flex w-full rounded-lg px-3 py-2.5 text-left text-sm font-semibold ${path === href ? 'bg-zinc-950 text-white' : 'text-zinc-600 hover:bg-zinc-100'}`}>{label}</button>)}</nav><div className="mt-auto border-t border-zinc-100 pt-4"><button type="button" onClick={() => onNavigate('/billing')} className="w-full rounded-lg px-3 py-2 text-left text-sm text-zinc-600 hover:bg-zinc-100">订阅与账单</button><button type="button" onClick={() => onNavigate('/settings')} className="mt-1 w-full rounded-lg px-3 py-2 text-left text-sm text-zinc-600 hover:bg-zinc-100">个人资料与设置</button><button type="button" onClick={onSignOut} className="mt-1 w-full rounded-lg px-3 py-2 text-left text-sm text-red-600 hover:bg-red-50">退出登录</button></div></aside>
    <div className="lg:pl-56"><header className="flex h-16 items-center justify-between border-b border-zinc-200 bg-white px-5 sm:px-8"><span className="text-sm font-semibold tracking-wide text-zinc-500">{pages.find(([href]) => href === path)?.[1] ?? '账户'}</span><div className="flex items-center gap-3"><button type="button" onClick={() => onNavigate('/notifications')} aria-label="通知" className="relative rounded-full p-2 text-zinc-600 hover:bg-zinc-100"><svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4 fill-none stroke-current stroke-[1.8]"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" strokeLinecap="round" strokeLinejoin="round" /></svg>{unread ? <span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-rose-500 ring-2 ring-white" aria-label="有未读通知" /> : null}</button><button type="button" onClick={() => onNavigate('/billing')} className="rounded-full border border-zinc-200 px-3 py-1.5 text-xs font-semibold text-zinc-700">订阅</button><button type="button" onClick={() => onNavigate('/settings')} aria-label="个人资料与设置" className="flex h-8 w-8 items-center justify-center overflow-hidden rounded-full bg-zinc-950 text-xs font-semibold text-white">{profile.avatarUrl ? <img src={profile.avatarUrl} alt="" className="h-full w-full object-cover" /> : avatarInitial}</button></div></header><main className="mx-auto max-w-6xl px-5 py-8 sm:px-8">{children}</main></div>
    <nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t border-zinc-200 bg-white lg:hidden" aria-label="移动端主导航">{pages.map(([href, label]) => <button key={href} type="button" onClick={() => onNavigate(href)} className={`min-h-14 text-[11px] font-semibold ${path === href ? 'text-red-600' : 'text-zinc-500'}`}>{label}</button>)}</nav>
  </div>;
}
