import type { ReactNode } from 'react';

const pages = [
  ['/app', 'NOW'], ['/app/tasks', 'TASKS'], ['/app/plan', 'PLAN'], ['/app/ops', 'OPS'], ['/app/review', 'REVIEW'],
] as const;

export function V2AppShell({ path, children, onNavigate, onSignOut, onNotifications }: { path: string; children: ReactNode; onNavigate: (path: string) => void; onSignOut: () => void; onNotifications: () => void }) {
  return <div className="min-h-screen bg-[#fafafa] text-zinc-900">
    <aside className="fixed inset-y-0 left-0 hidden w-56 border-r border-zinc-200 bg-white px-4 py-5 lg:flex lg:flex-col"><button type="button" onClick={() => onNavigate('/app')} className="flex items-center gap-2.5 px-2 text-left text-base font-semibold"><img src="/logo.png" alt="Visual Deadline" className="h-8 w-8 object-contain" />Visual Deadline</button><nav className="mt-10 space-y-1" aria-label="Primary"><span className="px-2 text-[11px] font-semibold tracking-[.16em] text-zinc-400">WORKSPACE</span>{pages.map(([href, label]) => <button key={href} type="button" onClick={() => onNavigate(href)} aria-current={path === href ? 'page' : undefined} className={`mt-1 flex w-full rounded-lg px-3 py-2.5 text-left text-sm font-semibold ${path === href ? 'bg-zinc-950 text-white' : 'text-zinc-600 hover:bg-zinc-100'}`}>{label}</button>)}</nav><div className="mt-auto border-t border-zinc-100 pt-4"><button type="button" onClick={() => onNavigate('/billing')} className="w-full rounded-lg px-3 py-2 text-left text-sm text-zinc-600 hover:bg-zinc-100">Subscription</button><button type="button" onClick={() => onNavigate('/settings')} className="mt-1 w-full rounded-lg px-3 py-2 text-left text-sm text-zinc-600 hover:bg-zinc-100">Profile & settings</button><button type="button" onClick={onSignOut} className="mt-1 w-full rounded-lg px-3 py-2 text-left text-sm text-red-600 hover:bg-red-50">Sign out</button></div></aside>
    <div className="lg:pl-56"><header className="flex h-16 items-center justify-between border-b border-zinc-200 bg-white px-5 sm:px-8"><span className="text-sm font-semibold tracking-wide text-zinc-500">{pages.find(([href]) => href === path)?.[1] ?? 'ACCOUNT'}</span><div className="flex items-center gap-3"><button type="button" onClick={onNotifications} aria-label="Notifications" className="rounded-full p-2 text-zinc-600 hover:bg-zinc-100"><svg viewBox="0 0 24 24" aria-hidden="true" className="h-4 w-4 fill-none stroke-current stroke-[1.8]"><path d="M18 9a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" strokeLinecap="round" strokeLinejoin="round" /></svg></button><button type="button" onClick={() => onNavigate('/billing')} className="rounded-full border border-zinc-200 px-3 py-1.5 text-xs font-semibold text-zinc-700">Free</button><button type="button" onClick={() => onNavigate('/settings')} aria-label="Profile and settings" className="flex h-8 w-8 items-center justify-center rounded-full bg-zinc-950 text-xs font-semibold text-white">VD</button></div></header><main className="mx-auto max-w-6xl px-5 py-8 sm:px-8">{children}</main></div>
    <nav className="fixed inset-x-0 bottom-0 z-20 grid grid-cols-5 border-t border-zinc-200 bg-white lg:hidden" aria-label="Primary mobile">{pages.map(([href, label]) => <button key={href} type="button" onClick={() => onNavigate(href)} className={`min-h-14 text-[11px] font-semibold ${path === href ? 'text-red-600' : 'text-zinc-500'}`}>{label}</button>)}</nav>
  </div>;
}
