import { randomBytes } from 'node:crypto';
import { assertAdminRole, assertOwner } from './domain.js';
import { appendAudit, findActiveAccountControl, findAdminRole } from './repository.js';
import { requireAuthenticatedUser, serviceJson, sha256 } from './runtime.js';

export async function requireAdmin(request, allowed) { const user = await requireAuthenticatedUser(request); const role = await findAdminRole(user.id); assertAdminRole(role, allowed); const control = await findActiveAccountControl(user.id); if (control?.status === 'banned') throw new Error('ACCOUNT_BLOCKED'); return { user, role }; }
export async function requireOwner(request) { const context = await requireAdmin(request, ['owner']); assertOwner(context.role); return context; }
export function makeInviteCode() { return `VD-${randomBytes(9).toString('base64url').toUpperCase()}`; }
export async function audit(context, requestId, action, targetType, targetId, after, reason, before) { await appendAudit({ actor_user_id: context.user.id, action, target_type: targetType, target_id: String(targetId), reason: reason || null, before_json: before || null, after_json: after || null, request_id: requestId }); }
export async function effectiveEntitlement(userId, at = new Date().toISOString()) { const rows = await serviceJson(`/rest/v1/entitlements?user_id=eq.${encodeURIComponent(userId)}&capability=eq.vd.plus&status=eq.active&valid_from=lte.${encodeURIComponent(at)}&or=(valid_until.is.null,valid_until.gt.${encodeURIComponent(at)})&order=valid_until.desc.nullsfirst`); return { allowed: Array.isArray(rows) && rows.length > 0, capability: 'vd.plus', sources: rows || [], validUntil: rows?.[0]?.valid_until || undefined }; }
export async function grantEntitlement(context, requestId, input) {
  const userId = typeof input.userId === 'string' ? input.userId : ''; const validFrom = typeof input.validFrom === 'string' ? input.validFrom : new Date().toISOString(); const durationDays = [1, 7, 30, 90].includes(input.durationDays) ? input.durationDays : undefined; const validUntil = input.permanent ? null : typeof input.validUntil === 'string' ? input.validUntil : durationDays ? new Date(Date.parse(validFrom) + durationDays * 86_400_000).toISOString() : ''; if (input.permanent) assertOwner(context.role); if (!userId || (!input.permanent && !validUntil)) throw new Error('ADMIN_INPUT_INVALID');
  const grantType = ['beta', 'compensation', 'promotion', 'manual', 'testing'].includes(input.grantType) ? input.grantType : 'manual';
  const [grant] = await serviceJson('/rest/v1/admin_access_grants', { method: 'POST', body: JSON.stringify({ user_id: userId, capability: 'vd.plus', valid_from: validFrom, valid_until: validUntil || null, grant_type: grantType, reason: String(input.reason || 'admin_grant').slice(0, 500), note: typeof input.note === 'string' ? input.note.slice(0, 2000) : null, created_by: context.user.id }) });
  const [entitlement] = await serviceJson('/rest/v1/entitlements', { method: 'POST', headers: { Prefer: 'resolution=merge-duplicates,return=representation' }, body: JSON.stringify({ user_id: userId, capability: 'vd.plus', source_type: 'admin_grant', source_id: grant.id, status: 'active', valid_from: validFrom, valid_until: validUntil || null, reason: `admin_${grantType}` }) });
  await audit(context, requestId, 'membership_grant', 'admin_access_grant', grant.id, grant, input.reason); return { grant, entitlement, effective: await effectiveEntitlement(userId) };
}
export async function revokeEntitlement(context, requestId, grantId, reason) { const [grant] = await serviceJson(`/rest/v1/admin_access_grants?id=eq.${encodeURIComponent(grantId)}&select=*`, {}); if (!grant) throw new Error('ADMIN_NOT_FOUND'); const [revoked] = await serviceJson(`/rest/v1/admin_access_grants?id=eq.${encodeURIComponent(grantId)}`, { method: 'PATCH', body: JSON.stringify({ revoked_at: new Date().toISOString(), revoked_by: context.user.id, revoke_reason: String(reason || 'admin_revoke').slice(0, 500) }) }); await serviceJson(`/rest/v1/entitlements?user_id=eq.${encodeURIComponent(grant.user_id)}&capability=eq.vd.plus&source_type=eq.admin_grant&source_id=eq.${encodeURIComponent(grantId)}`, { method: 'PATCH', body: JSON.stringify({ status: 'revoked', reason: `admin_grant_revoked:${String(reason || 'admin_revoke').slice(0, 300)}`) }); await audit(context, requestId, 'membership_revoke', 'admin_access_grant', grantId, revoked, reason, grant); return { grant: revoked, effective: await effectiveEntitlement(grant.user_id) }; }
export async function createInvite(context, requestId, input) { const code = makeInviteCode(); const [invite] = await serviceJson('/rest/v1/invite_codes', { method: 'POST', body: JSON.stringify({ code_hash: sha256(code), display_prefix: code.slice(0, 7), cohort_id: input.cohortId || null, max_uses: Number.isInteger(input.maxUses) ? input.maxUses : 1, expires_at: input.expiresAt || null, note: typeof input.note === 'string' ? input.note.slice(0, 1000) : null, created_by: context.user.id }) }); await audit(context, requestId, 'invite_create', 'invite_code', invite.id, { ...invite, code_hash: undefined }); return { invite: { ...invite, code }, requestId }; }
