import { normalizeOpsState } from './normalization.js';
import type { OpsAllocation, OpsExecutionPlan, OpsPlanDiff, OpsState, OpsTaskConfig } from './types.js';

const nowId = (prefix: string, now: string) => `${prefix}-${now.replace(/[^0-9]/g, '').slice(0, 14)}`;
const bounded = <T extends { createdAt: string }>(plans: T[]) => [...plans].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 20);

export function addOpsProposal(state: OpsState, proposal: OpsExecutionPlan, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, plans: bounded([...base.plans.filter((plan) => plan.id !== proposal.id), proposal]), proposedPlanId: proposal.id, updatedAt: now }; }
export function acceptOpsPlan(state: OpsState, planId: string, now: string): OpsState { const base = normalizeOpsState(state, now); if (base.proposedPlanId !== planId || !base.plans.some((plan) => plan.id === planId && plan.status === 'proposed')) return base; return { ...base, plans: bounded(base.plans.map((plan) => plan.id === planId ? { ...plan, status: 'accepted' as const } : plan.id === base.acceptedPlanId ? { ...plan, status: 'superseded' as const } : plan)), acceptedPlanId: planId, proposedPlanId: undefined, updatedAt: now }; }
export function rejectOpsPlan(state: OpsState, planId: string, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, plans: base.plans.map((plan) => plan.id === planId && plan.status === 'proposed' ? { ...plan, status: 'rejected' as const } : plan), proposedPlanId: base.proposedPlanId === planId ? undefined : base.proposedPlanId, updatedAt: now }; }

export function diffOpsPlans(accepted: OpsExecutionPlan | undefined, proposed: OpsExecutionPlan | undefined): OpsPlanDiff {
  const empty: OpsPlanDiff = { unchanged: [], newlyScheduled: [], moved: [], removed: [], newlyUnscheduled: [], deadlineMisses: proposed?.warnings.filter((warning) => warning.startsWith('DEADLINE_MISS:')).map((warning) => warning.slice(14)) ?? [], conflicts: [] }; if (!proposed) return empty;
  const old = new Map((accepted?.allocations ?? []).map((allocation) => [allocation.taskId, allocation])); const next = new Map(proposed.allocations.map((allocation) => [allocation.taskId, allocation]));
  next.forEach((allocation, taskId) => { const before = old.get(taskId); if (!before) empty.newlyScheduled.push(taskId); else if (before.start === allocation.start && before.end === allocation.end && before.executorId === allocation.executorId) empty.unchanged.push(taskId); else empty.moved.push(taskId); }); old.forEach((_, taskId) => { if (!next.has(taskId)) empty.removed.push(taskId); }); empty.newlyUnscheduled = proposed.unscheduled.map((entry) => entry.taskId); return empty;
}

export function upsertOpsTaskConfig(state: OpsState, config: OpsTaskConfig, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, taskConfigs: [...base.taskConfigs.filter((entry) => entry.taskId !== config.taskId), { ...config, updatedAt: now }], updatedAt: now }; }
export function upsertManualAllocation(state: OpsState, allocation: OpsAllocation, now: string): OpsState { const base = normalizeOpsState(state, now); if (!base.executors.some((executor) => executor.id === allocation.executorId) || Date.parse(allocation.end) <= Date.parse(allocation.start) || allocation.elapsedMinutes <= 0 || allocation.effortMinutes <= 0) throw new Error('手动排期缺少有效执行者、时段或时长。'); const current = base.plans.find((plan) => plan.id === base.acceptedPlanId); const plan: OpsExecutionPlan = current ? { ...current, allocations: [...current.allocations.filter((entry) => entry.taskId !== allocation.taskId), { ...allocation, source: 'manual' }], createdAt: now } : { id: nowId('ops-manual', now), version: Math.max(0, ...base.plans.map((entry) => entry.version)) + 1, status: 'accepted', horizonStart: allocation.start, horizonEnd: allocation.end, allocations: [{ ...allocation, source: 'manual' }], unscheduled: [], warnings: [], createdAt: now }; const plans = bounded([...base.plans.filter((entry) => entry.id !== plan.id), plan]); return { ...base, plans, acceptedPlanId: plan.id, updatedAt: now }; }
export function deleteTaskFromOpsState(state: OpsState, taskId: string, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, taskConfigs: base.taskConfigs.filter((entry) => entry.taskId !== taskId), plans: base.plans.map((plan) => ({ ...plan, allocations: plan.allocations.filter((allocation) => allocation.taskId !== taskId), unscheduled: plan.unscheduled.filter((entry) => entry.taskId !== taskId) })), updatedAt: now }; }
export function deleteOpsExecutor(state: OpsState, executorId: string, now: string): OpsState { const base = normalizeOpsState(state, now); if (executorId === 'self') throw new Error('默认执行者不能删除。'); return { ...base, executors: base.executors.filter((executor) => executor.id !== executorId), commitments: base.commitments.filter((commitment) => commitment.executorId !== executorId), taskConfigs: base.taskConfigs.map((config) => config.executorId === executorId ? { ...config, executorId: undefined, updatedAt: now } : config), plans: base.plans.map((plan) => ({ ...plan, allocations: plan.allocations.filter((allocation) => allocation.executorId !== executorId) })), updatedAt: now }; }
