import { normalizeOpsState } from './normalization.js';
import type { OpsAllocation, OpsExecutionPlan, OpsPlanDiff, OpsState, OpsTaskConfig } from './types.js';
import type { Task } from '../../types/task.js';
import { buildExecutorAvailability, detectOpsConflicts } from './scheduler.js';
import { projectTaskDependencyGraph } from './dependencies.js';

const nowId = (prefix: string, now: string) => `${prefix}-${now.replace(/[^0-9]/g, '').slice(0, 14)}`;
const bounded = <T extends { createdAt: string }>(plans: T[]) => [...plans].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 20);

export function addOpsProposal(state: OpsState, proposal: OpsExecutionPlan, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, plans: bounded([...base.plans.map((plan) => plan.status === 'proposed' ? { ...plan, status: 'rejected' as const } : plan).filter((plan) => plan.id !== proposal.id), proposal]), proposedPlanId: proposal.id, updatedAt: now }; }
export function acceptOpsPlan(state: OpsState, planId: string, now: string): OpsState { const base = normalizeOpsState(state, now); if (base.proposedPlanId !== planId || !base.plans.some((plan) => plan.id === planId && plan.status === 'proposed')) return base; return { ...base, plans: bounded(base.plans.map((plan) => plan.id === planId ? { ...plan, status: 'accepted' as const } : plan.id === base.acceptedPlanId ? { ...plan, status: 'superseded' as const } : plan)), acceptedPlanId: planId, proposedPlanId: undefined, updatedAt: now }; }
export function rejectOpsPlan(state: OpsState, planId: string, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, plans: base.plans.map((plan) => plan.id === planId && plan.status === 'proposed' ? { ...plan, status: 'rejected' as const } : plan), proposedPlanId: base.proposedPlanId === planId ? undefined : base.proposedPlanId, updatedAt: now }; }

export function diffOpsPlans(accepted: OpsExecutionPlan | undefined, proposed: OpsExecutionPlan | undefined, conflicts: readonly string[] = []): OpsPlanDiff {
  const empty: OpsPlanDiff = { unchanged: [], newlyScheduled: [], moved: [], removed: [], newlyUnscheduled: [], deadlineMisses: proposed?.warnings.filter((warning) => warning.startsWith('DEADLINE_MISS:')).map((warning) => warning.slice(14)) ?? [], conflicts: [...conflicts] }; if (!proposed) return empty;
  const old = new Map((accepted?.allocations ?? []).map((allocation) => [allocation.taskId, allocation])); const next = new Map(proposed.allocations.map((allocation) => [allocation.taskId, allocation]));
  next.forEach((allocation, taskId) => { const before = old.get(taskId); if (!before) empty.newlyScheduled.push(taskId); else if (before.start === allocation.start && before.end === allocation.end && before.executorId === allocation.executorId) empty.unchanged.push(taskId); else empty.moved.push(taskId); }); old.forEach((_, taskId) => { if (!next.has(taskId)) empty.removed.push(taskId); }); empty.newlyUnscheduled = proposed.unscheduled.map((entry) => entry.taskId); return empty;
}

export function upsertOpsTaskConfig(state: OpsState, config: OpsTaskConfig, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, taskConfigs: [...base.taskConfigs.filter((entry) => entry.taskId !== config.taskId), { ...config, updatedAt: now }], updatedAt: now }; }
export function validateManualAllocation(state: OpsState, tasks: readonly Task[], allocation: OpsAllocation): string | undefined {
  const base = normalizeOpsState(state); const task = tasks.find((entry) => entry.id === allocation.taskId); const executor = base.executors.find((entry) => entry.id === allocation.executorId); const start = Date.parse(allocation.start); const end = Date.parse(allocation.end);
  if (!task || task.lifecycleStatus !== 'active') return '任务不存在或不处于进行中状态。'; if (!executor || !executor.active) return '执行者不存在或未启用。'; if (!Number.isFinite(start) || !Number.isFinite(end) || end <= start || allocation.elapsedMinutes <= 0 || allocation.effortMinutes <= 0) return '手动排期缺少有效的起止时间或时长。';
  if (!buildExecutorAvailability(base, executor.id, start, end).some(([windowStart, windowEnd]) => windowStart <= start && windowEnd >= end)) return '手动排期不在执行者可用时段内。';
  if (base.commitments.some((commitment) => commitment.executorId === executor.id && start < Date.parse(commitment.end) && end > Date.parse(commitment.start))) return '手动排期与固定事项冲突。';
  const current = base.plans.find((plan) => plan.id === base.acceptedPlanId); const candidate: OpsExecutionPlan = current ? { ...current, allocations: [...current.allocations.filter((entry) => entry.taskId !== allocation.taskId), allocation] } : { id: 'manual-validation', version: 1, status: 'accepted', horizonStart: allocation.start, horizonEnd: allocation.end, allocations: [allocation], unscheduled: [], warnings: [], createdAt: allocation.start };
  const graph = new Map(projectTaskDependencyGraph(tasks).map((entry) => [entry.taskId, entry]));
  for (const predecessor of graph.get(task.id)?.predecessors ?? []) { if (predecessor.state === 'missing' || predecessor.state === 'self' || predecessor.state === 'cycle' || predecessor.state === 'abandoned') return '手动排期的前置任务不满足。'; if (predecessor.state === 'active') { const predecessorAllocation = candidate.allocations.find((entry) => entry.taskId === predecessor.taskId); if (!predecessorAllocation || Date.parse(predecessorAllocation.end) > start) return '手动排期早于前置任务完成时间。'; } }
  const conflicts = detectOpsConflicts(candidate, tasks, base).filter((conflict) => /CAPACITY_CONFLICT|COMMITMENT_COLLISION|OUTSIDE_AVAILABILITY|DEPENDENCY_TIMING|ACTIVE_PREDECESSOR/.test(conflict)); return conflicts.length ? '手动排期违反容量或依赖约束。' : undefined;
}
export function upsertManualAllocation(state: OpsState, tasks: readonly Task[], allocation: OpsAllocation, now: string): OpsState { const base = normalizeOpsState(state, now); const error = validateManualAllocation(base, tasks, allocation); if (error) throw new Error(error); const current = base.plans.find((plan) => plan.id === base.acceptedPlanId); const plan: OpsExecutionPlan = current ? { ...current, allocations: [...current.allocations.filter((entry) => entry.taskId !== allocation.taskId), { ...allocation, source: 'manual' }], createdAt: now } : { id: nowId('ops-manual', now), version: Math.max(0, ...base.plans.map((entry) => entry.version)) + 1, status: 'accepted', horizonStart: allocation.start, horizonEnd: allocation.end, allocations: [{ ...allocation, source: 'manual' }], unscheduled: [], warnings: [], createdAt: now }; const plans = bounded([...base.plans.filter((entry) => entry.id !== plan.id), plan]); return { ...base, plans, acceptedPlanId: plan.id, updatedAt: now }; }
export function setOpsAllocationLocked(state: OpsState, taskId: string, locked: boolean, now: string): OpsState { const base = normalizeOpsState(state, now); if (!base.acceptedPlanId) return base; return { ...base, plans: base.plans.map((plan) => plan.id === base.acceptedPlanId ? { ...plan, allocations: plan.allocations.map((allocation) => allocation.taskId === taskId ? { ...allocation, locked } : allocation) } : plan), updatedAt: now }; }
export function updateOpsExecutor(state: OpsState, executorId: string, patch: Pick<OpsState['executors'][number], 'name' | 'kind' | 'active' | 'maxParallel'>, now: string): OpsState { const base = normalizeOpsState(state, now); if (!patch.name.trim() || !Number.isInteger(patch.maxParallel) || patch.maxParallel < 1) throw new Error('执行者名称和最大并行数无效。'); return { ...base, executors: base.executors.map((executor) => executor.id === executorId ? { ...executor, ...patch, name: patch.name.trim() } : executor), updatedAt: now }; }
export function deleteOpsAvailability(state: OpsState, executorId: string, availabilityId: string, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, executors: base.executors.map((executor) => executor.id === executorId ? { ...executor, availability: executor.availability.filter((window) => window.id !== availabilityId) } : executor), updatedAt: now }; }
export function deleteTaskFromOpsState(state: OpsState, taskId: string, now: string): OpsState { const base = normalizeOpsState(state, now); return { ...base, taskConfigs: base.taskConfigs.filter((entry) => entry.taskId !== taskId), plans: base.plans.map((plan) => ({ ...plan, allocations: plan.allocations.filter((allocation) => allocation.taskId !== taskId), unscheduled: plan.unscheduled.filter((entry) => entry.taskId !== taskId) })), updatedAt: now }; }
export function deleteOpsExecutor(state: OpsState, executorId: string, now: string): OpsState { const base = normalizeOpsState(state, now); if (executorId === 'self') throw new Error('默认执行者不能删除。'); return { ...base, executors: base.executors.filter((executor) => executor.id !== executorId), commitments: base.commitments.filter((commitment) => commitment.executorId !== executorId), taskConfigs: base.taskConfigs.map((config) => config.executorId === executorId ? { ...config, executorId: undefined, updatedAt: now } : config), plans: base.plans.map((plan) => ({ ...plan, allocations: plan.allocations.filter((allocation) => allocation.executorId !== executorId) })), updatedAt: now }; }
